import type { CuratedQuestion, GameWord, MatchPack, TrueFalseFact } from '../games-content';
import type { GameLevel } from '../games';

/**
 * EduGames content for lower primary: Primary 1–3 (ages 6–8), also fine for
 * nursery and KG children. Very short sentences, simple words and emoji so
 * children who are just learning to read can still play. NERDC Basic
 * Education themes, Nigerian names and places, British spelling.
 *
 * Quiz questions list the right answer first (`a`) and three wrong ones (`w`).
 */

const LEVEL: GameLevel = 'PRIMARY';

type QRow = [q: string, a: string, w: [string, string, string], explain?: string];
type FRow = [statement: string, answer: boolean, explain: string];
type WRow = [word: string, meaning: string, sentence: string];

const qs = (prefix: string, subject: string, topic: string, years: number[], rows: QRow[]): CuratedQuestion[] =>
  rows.map(([q, a, w, explain], i) => ({ id: `lp-${prefix}-${i + 1}`, level: LEVEL, subject, topic, q, a, w, explain, years }));

const fs = (prefix: string, subject: string, topic: string, years: number[], rows: FRow[]): TrueFalseFact[] =>
  rows.map(([statement, answer, explain], i) => ({ id: `lp-${prefix}-${i + 1}`, level: LEVEL, subject, topic, statement, answer, explain, years }));

const ws = (years: number[], subject: string | undefined, rows: WRow[]): GameWord[] =>
  rows.map(([word, meaning, sentence]) => ({ word, level: LEVEL, meaning, sentence, subject, years }));

// ------------------------------------------------------------ match packs

export const LOWER_PRIMARY_MATCH_PACKS: MatchPack[] = [
  {
    id: 'lp-animal-homes',
    title: 'Animals and their homes',
    subject: 'Basic Science',
    levels: ['PRIMARY'],
    leftLabel: 'Animal',
    rightLabel: 'Home',
    years: [1, 2, 3],
    pairs: [
      ['Bird 🐦', 'Nest'],
      ['Bee 🐝', 'Hive'],
      ['Spider 🕷️', 'Web'],
      ['Horse 🐴', 'Stable'],
      ['Dog 🐕', 'Kennel'],
      ['Lion 🦁', 'Den'],
      ['Fish 🐟', 'Water'],
      ['Rabbit 🐇', 'Burrow'],
      ['Hen 🐔', 'Coop'],
      ['Pig 🐖', 'Sty'],
      ['Snail 🐌', 'Shell'],
      ['Monkey 🐒', 'Tree'],
    ],
  },
  {
    id: 'lp-animal-sounds',
    title: 'Animals and their sounds',
    subject: 'Basic Science',
    levels: ['PRIMARY'],
    leftLabel: 'Animal',
    rightLabel: 'Sound',
    years: [1, 2],
    pairs: [
      ['Dog 🐕', 'Barks'],
      ['Cat 🐈', 'Mews'],
      ['Cow 🐄', 'Moos'],
      ['Goat 🐐', 'Bleats'],
      ['Lion 🦁', 'Roars'],
      ['Hen 🐔', 'Clucks'],
      ['Duck 🦆', 'Quacks'],
      ['Horse 🐴', 'Neighs'],
      ['Snake 🐍', 'Hisses'],
      ['Bee 🐝', 'Buzzes'],
      ['Owl 🦉', 'Hoots'],
      ['Frog 🐸', 'Croaks'],
      ['Donkey', 'Brays'],
      ['Pig 🐖', 'Grunts'],
    ],
  },
  {
    id: 'lp-number-words',
    title: 'Numbers 1 to 20 in words',
    subject: 'Mathematics',
    levels: ['PRIMARY'],
    leftLabel: 'Number',
    rightLabel: 'Word',
    years: [1, 2],
    pairs: [
      ['1', 'one'],
      ['2', 'two'],
      ['3', 'three'],
      ['4', 'four'],
      ['5', 'five'],
      ['6', 'six'],
      ['7', 'seven'],
      ['8', 'eight'],
      ['9', 'nine'],
      ['10', 'ten'],
      ['11', 'eleven'],
      ['12', 'twelve'],
      ['13', 'thirteen'],
      ['14', 'fourteen'],
      ['15', 'fifteen'],
      ['16', 'sixteen'],
      ['17', 'seventeen'],
      ['18', 'eighteen'],
      ['19', 'nineteen'],
      ['20', 'twenty'],
    ],
  },
  {
    id: 'lp-tens-hundreds',
    title: 'Tens, hundreds and a thousand',
    subject: 'Mathematics',
    levels: ['PRIMARY'],
    leftLabel: 'Number',
    rightLabel: 'Word',
    years: [2, 3],
    pairs: [
      ['30', 'thirty'],
      ['40', 'forty'],
      ['50', 'fifty'],
      ['60', 'sixty'],
      ['70', 'seventy'],
      ['80', 'eighty'],
      ['90', 'ninety'],
      ['100', 'one hundred'],
      ['200', 'two hundred'],
      ['500', 'five hundred'],
      ['1000', 'one thousand'],
      ['45', 'forty-five'],
      ['99', 'ninety-nine'],
      ['250', 'two hundred and fifty'],
    ],
  },
  {
    id: 'lp-shapes',
    title: 'Shapes and their clues',
    subject: 'Mathematics',
    levels: ['PRIMARY'],
    leftLabel: 'Shape',
    rightLabel: 'Clue',
    years: [1, 2, 3],
    pairs: [
      ['Triangle', '3 sides and 3 corners'],
      ['Square', '4 equal sides'],
      ['Rectangle', '2 long sides and 2 short sides'],
      ['Circle', 'Round and flat, no corners'],
      ['Pentagon', '5 sides'],
      ['Hexagon', '6 sides'],
      ['Octagon', '8 sides'],
      ['Cube', 'Like a dice 🎲'],
      ['Sphere', 'Like a ball ⚽'],
      ['Cylinder', 'Like a tin of milk'],
      ['Cone', 'Like an ice cream cone 🍦'],
    ],
  },
  {
    id: 'lp-more-opposites',
    title: 'More opposites',
    subject: 'English Language',
    levels: ['PRIMARY'],
    leftLabel: 'Word',
    rightLabel: 'Opposite',
    years: [1, 2, 3],
    pairs: [
      ['Big', 'Small'],
      ['Tall', 'Short'],
      ['Heavy', 'Light'],
      ['Clean', 'Dirty'],
      ['Hard', 'Soft'],
      ['Thick', 'Thin'],
      ['Come', 'Go'],
      ['Laugh', 'Cry'],
      ['Sit', 'Stand'],
      ['Give', 'Take'],
      ['Near', 'Far'],
      ['Good', 'Bad'],
      ['Right', 'Wrong'],
      ['Strong', 'Weak'],
      ['Rich', 'Poor'],
      ['First', 'Last'],
    ],
  },
  {
    id: 'lp-plurals',
    title: 'One and many',
    subject: 'English Language',
    levels: ['PRIMARY'],
    leftLabel: 'One',
    rightLabel: 'Many',
    years: [2, 3],
    pairs: [
      ['child', 'children'],
      ['man', 'men'],
      ['woman', 'women'],
      ['foot', 'feet'],
      ['tooth', 'teeth'],
      ['mouse', 'mice'],
      ['box', 'boxes'],
      ['baby', 'babies'],
      ['leaf', 'leaves'],
      ['knife', 'knives'],
      ['bus', 'buses'],
      ['tomato', 'tomatoes'],
      ['goose', 'geese'],
      ['lady', 'ladies'],
    ],
  },
  {
    id: 'lp-helpers',
    title: 'Community helpers',
    subject: 'Social Studies',
    levels: ['PRIMARY'],
    leftLabel: 'Helper',
    rightLabel: 'What they do',
    years: [1, 2, 3],
    pairs: [
      ['Doctor', 'Treats sick people'],
      ['Teacher', 'Teaches children'],
      ['Farmer', 'Grows food'],
      ['Tailor', 'Sews clothes'],
      ['Barber', 'Cuts hair'],
      ['Mechanic', 'Repairs cars'],
      ['Carpenter', 'Makes chairs and tables'],
      ['Firefighter', 'Puts out fires'],
      ['Police officer', 'Keeps us safe'],
      ['Pilot', 'Flies an aeroplane'],
      ['Baker', 'Bakes bread'],
      ['Cobbler', 'Mends shoes'],
      ['Driver', 'Drives a bus or car'],
      ['Nurse', 'Cares for patients'],
    ],
  },
  {
    id: 'lp-body-parts',
    title: 'Body parts and what they do',
    subject: 'Basic Science',
    levels: ['PRIMARY'],
    leftLabel: 'Body part',
    rightLabel: 'What it does',
    years: [1, 2, 3],
    pairs: [
      ['Eyes 👀', 'See'],
      ['Ears 👂', 'Hear'],
      ['Nose 👃', 'Smell'],
      ['Tongue 👅', 'Taste'],
      ['Skin', 'Feel hot and cold'],
      ['Legs 🦵', 'Walk'],
      ['Teeth 🦷', 'Chew food'],
      ['Hands ✋', 'Hold things'],
      ['Lungs', 'Breathe'],
      ['Heart', 'Pumps blood'],
    ],
  },
  {
    id: 'lp-colours',
    title: 'Colours of things',
    subject: 'Cultural and Creative Arts',
    levels: ['PRIMARY'],
    leftLabel: 'Thing',
    rightLabel: 'Colour',
    years: [1, 2],
    pairs: [
      ['Ripe banana 🍌', 'Yellow'],
      ['Grass 🌿', 'Green'],
      ['Clear sky', 'Blue'],
      ['Milk 🥛', 'White'],
      ['Charcoal', 'Black'],
      ['Ripe tomato 🍅', 'Red'],
      ['Carrot 🥕', 'Orange'],
      ['Chocolate 🍫', 'Brown'],
      ['Elephant 🐘', 'Grey'],
      ['Flamingo 🦩', 'Pink'],
    ],
  },
  {
    id: 'lp-months',
    title: 'Months of the year in order',
    subject: 'Mathematics',
    levels: ['PRIMARY'],
    leftLabel: 'Month',
    rightLabel: 'Place in the year',
    years: [2, 3],
    pairs: [
      ['January', '1st month'],
      ['February', '2nd month'],
      ['March', '3rd month'],
      ['April', '4th month'],
      ['May', '5th month'],
      ['June', '6th month'],
      ['July', '7th month'],
      ['August', '8th month'],
      ['September', '9th month'],
      ['October', '10th month'],
      ['November', '11th month'],
      ['December', '12th month'],
    ],
  },
];

// ------------------------------------------------------------ true or false facts

export const LOWER_PRIMARY_FACTS: TrueFalseFact[] = [
  ...fs('tm1', 'Mathematics', 'Numbers and counting', [1], [
    ['2 + 2 = 4', true, 'Two and two make four.'],
    ['5 + 3 = 9', false, '5 + 3 = 8.'],
    ['10 − 4 = 6', true, 'Take 4 away from 10 and 6 are left.'],
    ['9 is bigger than 12.', false, '12 is bigger than 9.'],
    ['20 comes after 19.', true, '19, then 20.'],
    ['1 + 0 = 10', false, 'Adding 0 changes nothing: 1 + 0 = 1.'],
    ['🍊🍊🍊🍊 There are 4 oranges here.', true, 'Count them: 1, 2, 3, 4.'],
    ['⭐⭐⭐ There are 5 stars here.', false, 'Count them: there are 3 stars.'],
  ]),
  ...fs('tm2', 'Mathematics', 'Place value', [2, 3], [
    ['3 tens is 30.', true, '10 + 10 + 10 = 30.'],
    ['In 64, the 6 means 6 tens.', true, 'The 6 is in the tens place, so it means 60.'],
    ['100 has three digits.', true, '1, 0 and 0: three digits.'],
    ['1000 is the same as ten hundreds.', true, '10 × 100 = 1000.'],
    ['7 is an even number.', false, '7 is odd. Even numbers end in 0, 2, 4, 6 or 8.'],
  ]),
  ...fs('tm3', 'Mathematics', 'Multiplication', [2, 3], [
    ['2 × 5 = 10', true, 'Two fives make ten.'],
    ['10 × 3 = 30', true, 'Three tens make thirty.'],
    ['5 × 5 = 20', false, '5 × 5 = 25.'],
    ['2 × 6 = 12', true, 'Six twos make twelve.'],
  ]),
  ...fs('tm4', 'Mathematics', 'Fractions', [2, 3], [
    ['Half of 10 is 5.', true, '5 + 5 = 10.'],
    ['Two quarters make one half.', true, '¼ + ¼ = ½.'],
    ['A quarter of 8 is 4.', false, 'A quarter of 8 is 2; half of 8 is 4.'],
  ]),
  ...fs('tm5', 'Mathematics', 'Shapes', [1, 2, 3], [
    ['A square has 4 corners.', true, 'A square has 4 sides and 4 corners.'],
    ['A circle has 3 corners.', false, 'A circle is round: it has no corners.'],
    ['A ball is shaped like a cube.', false, 'A ball is a sphere; a dice is a cube.'],
    ['A cube has 6 faces.', true, 'A dice has 6 faces, numbered 1 to 6.'],
  ]),
  ...fs('tm6', 'Mathematics', 'Time and calendar', [1, 2, 3], [
    ['There are 12 months in a year.', true, 'January to December: 12 months.'],
    ['There are 60 minutes in one hour.', true, '1 hour = 60 minutes.'],
    ['At half past 2, the long hand points to 6.', true, 'At half past, the long hand is on 6.'],
    ['At 5 o’clock, the long hand points to 12.', true, 'At o’clock, the long hand is on 12.'],
    ['The day after Friday is Saturday.', true, 'Friday, then Saturday.'],
    ['June comes before May.', false, 'May comes before June.'],
  ]),
  ...fs('tm7', 'Mathematics', 'Money and measurement', [1, 2, 3], [
    ['₦50 is more than ₦100.', false, '₦100 is more than ₦50.'],
    ['Two ₦10 notes make ₦20.', true, '₦10 + ₦10 = ₦20.'],
    ['An elephant is lighter than a goat.', false, 'An elephant is much heavier than a goat.'],
    ['We use a ruler to measure length.', true, 'A ruler shows how long something is.'],
  ]),

  ...fs('te1', 'English Language', 'Letters and sounds', [1, 2], [
    ['a, e, i, o and u are vowels.', true, 'The five vowels are a, e, i, o and u.'],
    ['“B” is a vowel.', false, 'B is a consonant.'],
    ['The English alphabet has 26 letters.', true, 'A to Z: 26 letters.'],
    ['“Ball” begins with the sound “d”.', false, '“Ball” begins with “b”.'],
    ['“Ship” begins with the “sh” sound.', true, 'Sh-ip: it starts with “sh”.'],
  ]),
  ...fs('te2', 'English Language', 'Rhyming words', [1, 2], [
    ['“Cat” rhymes with “hat”.', true, 'Both end with “-at”.'],
    ['“Dog” rhymes with “pen”.', false, '“Dog” rhymes with “log” and “frog”.'],
    ['“Cake” rhymes with “lake”.', true, 'Both end with “-ake”.'],
  ]),
  ...fs('te3', 'English Language', 'Grammar', [1, 2, 3], [
    ['We write “an” before “apple”.', true, '“Apple” starts with a vowel sound, so we say “an apple”.'],
    ['We say “a egg”.', false, 'We say “an egg”, because “egg” starts with a vowel sound.'],
    ['The plural of “child” is “childs”.', false, 'One child, many children.'],
    ['The opposite of “big” is “small”.', true, 'Big and small are opposites.'],
    ['“Run” is an action word.', true, 'Run tells us what someone does.'],
    ['The past tense of “go” is “goed”.', false, 'Today I go; yesterday I went.'],
  ]),
  ...fs('te4', 'English Language', 'Capital letters and punctuation', [1, 2, 3], [
    ['A sentence starts with a capital letter.', true, 'Every sentence begins with a capital letter.'],
    ['A question ends with a full stop.', false, 'A question ends with a question mark (?).'],
    ['Names of people begin with a capital letter.', true, 'We write Ade, Ngozi and Musa with capital letters.'],
    ['“Monday” begins with a capital letter.', true, 'Days of the week always start with a capital letter.'],
    ['When “I” means me, it is always a capital letter.', true, 'We write “I am happy”, never “i am happy”.'],
    ['“Tuesday” is spelt T-u-s-d-a-y.', false, 'It is spelt T-u-e-s-d-a-y.'],
  ]),

  ...fs('ts1', 'Basic Science', 'Our body and senses', [1, 2, 3], [
    ['We have two eyes.', true, 'We see with our two eyes.'],
    ['We hear with our nose.', false, 'We hear with our ears; we smell with our nose.'],
    ['The tongue helps us to taste food.', true, 'The tongue tells sweet from salty.'],
    ['We have five senses.', true, 'Sight, hearing, smell, taste and touch.'],
    ['We need air to live.', true, 'We breathe in air all the time.'],
    ['A baby grows into an adult.', true, 'Living things grow.'],
  ]),
  ...fs('ts2', 'Basic Science', 'Animals', [1, 2, 3], [
    ['A fish lives in water.', true, 'Fish live and breathe in water.'],
    ['A bird lays eggs.', true, 'Birds hatch from eggs.'],
    ['A cow eats meat.', false, 'A cow eats grass and leaves.'],
    ['A goat has four legs.', true, 'Goats walk on four legs.'],
    ['A hen has four legs.', false, 'A hen is a bird: it has two legs.'],
    ['A snake has legs.', false, 'A snake has no legs; it slides along.'],
    ['Bees make honey.', true, 'Bees make honey from flowers.'],
    ['A caterpillar turns into a butterfly.', true, 'A caterpillar grows and becomes a butterfly.'],
    ['A lion is a pet we keep at home.', false, 'A lion is a wild animal.'],
    ['A goat is a farm animal.', true, 'Many families in Nigeria keep goats.'],
    ['Spiders spin webs.', true, 'A spider makes a web to catch insects.'],
  ]),
  ...fs('ts3', 'Basic Science', 'Plants and living things', [1, 2, 3], [
    ['Plants need water to grow.', true, 'Without water, plants dry up.'],
    ['Roots grow under the soil.', true, 'Roots hold the plant and take in water.'],
    ['A stone is a living thing.', false, 'A stone does not eat, grow or breathe.'],
    ['A mango tree grows from a seed.', true, 'Plant a mango seed and a tree can grow.'],
  ]),
  ...fs('ts4', 'Basic Science', 'Weather and seasons', [1, 2, 3], [
    ['Nigeria has a rainy season and a dry season.', true, 'These are Nigeria’s two main seasons.'],
    ['The harmattan wind is dry and dusty.', true, 'It blows dust from the Sahara Desert.'],
    ['Harmattan comes in the rainy season.', false, 'Harmattan comes in the dry season.'],
    ['Rain falls from clouds.', true, 'Dark clouds bring rain.'],
    ['Ice melts when it gets warm.', true, 'Warm ice turns back into water.'],
    ['The sun gives us light and heat.', true, 'The sun lights and warms the earth.'],
  ]),
  ...fs('ts5', 'Basic Science', 'Health and safety', [1, 2, 3], [
    ['We should wash our hands after using the toilet.', true, 'Soap and water wash germs away.'],
    ['Brushing our teeth once a week is enough.', false, 'Brush your teeth every morning and night.'],
    ['Eating fruits is good for our health.', true, 'Fruits like oranges and pawpaw keep us healthy.'],
    ['It is safe to play with matches.', false, 'Matches can start a fire. Never play with them.'],
    ['We should drink clean water.', true, 'Dirty water can make us sick.'],
    ['Sleeping under a mosquito net helps to prevent malaria.', true, 'The net keeps mosquitoes off us at night.'],
    ['Eating too many sweets can hurt our teeth.', true, 'Sugar can cause holes in teeth.'],
  ]),

  ...fs('tx1', 'Social Studies', 'Family and school', [1, 2, 3], [
    ['Your father’s father is your grandfather.', true, 'Your parents’ fathers are your grandfathers.'],
    ['Your aunt is the sister of your mother or father.', true, 'Your parents’ sisters are your aunts.'],
    ['A family can have a father, a mother and children.', true, 'Families come in many sizes.'],
    ['The head teacher is the head of a primary school.', true, 'The head teacher leads the school.'],
    ['Pupils should obey school rules.', true, 'Rules keep everyone safe and happy.'],
    ['A market is where people buy and sell.', true, 'We buy food and other things at the market.'],
  ]),
  ...fs('tx2', 'Social Studies', 'Community helpers', [1, 2, 3], [
    ['A doctor treats sick people.', true, 'Doctors help sick people get well.'],
    ['A farmer grows food.', true, 'Farmers grow yam, rice, maize and more.'],
    ['A tailor repairs cars.', false, 'A tailor sews clothes; a mechanic repairs cars.'],
    ['A firefighter puts out fires.', true, 'Firefighters use water to stop fires.'],
    ['The police help to keep us safe.', true, 'Police officers protect people.'],
  ]),
  ...fs('tx3', 'Civic Education', 'National symbols', [1, 2, 3], [
    ['The Nigerian flag is green, white and green.', true, 'Green, white, green: three bands.'],
    ['There is red on the Nigerian flag.', false, 'The flag is only green and white.'],
    ['There is an eagle on Nigeria’s coat of arms.', true, 'A red eagle stands on top of the shield.'],
  ]),
  ...fs('tx4', 'Civic Education', 'Good manners and safety', [1, 2, 3], [
    ['We should say “thank you” when we get a gift.', true, 'Saying thank you is good manners.'],
    ['It is good manners to greet elders.', true, 'We greet elders with respect.'],
    ['It is fine to go with a stranger who gives you sweets.', false, 'Say no, and tell a trusted adult.'],
    ['We should cross the road at a zebra crossing.', true, 'A zebra crossing is a safe place to cross.'],
    ['It is safe to play on the road.', false, 'Play in the playground, away from cars.'],
    ['A red traffic light means “go”.', false, 'Red means stop; green means go.'],
    ['We should wear a seat belt in a car.', true, 'A seat belt keeps us safe.'],
    ['We should throw rubbish into the gutter.', false, 'Put rubbish in a dustbin; it blocks gutters.'],
  ]),

  ...fs('tv1', 'Verbal Reasoning', 'Odd one out and patterns', [1, 2, 3], [
    ['In “dog, cat, goat, chair”, the odd one out is “chair”.', true, 'A chair is not an animal.'],
    ['In the alphabet, A comes after B.', false, 'A comes first, then B.'],
    ['2, 4, 6, 8 … the next number is 10.', true, 'Add 2 each time.'],
    ['Monday, Tuesday … the next day is Thursday.', false, 'After Tuesday comes Wednesday.'],
    ['Hen, duck and eagle are all birds.', true, 'They all have feathers and wings.'],
  ]),
];

// ------------------------------------------------------------ quiz questions

export const LOWER_PRIMARY_QUESTIONS: CuratedQuestion[] = [
  // ---------------- Mathematics
  ...qs('mc', 'Mathematics', 'Counting', [1], [
    ['How many 🍊 are here? 🍊🍊🍊', '3', ['2', '4', '5'], 'Count them: 1, 2, 3.'],
    ['How many ⭐ are here? ⭐⭐⭐⭐⭐', '5', ['4', '6', '3'], 'Count them: 1, 2, 3, 4, 5.'],
    ['How many 🐐 are here? 🐐🐐🐐🐐🐐🐐🐐', '7', ['6', '8', '5'], 'Count them one by one: there are 7.'],
    ['How many 🥭 are here? 🥭🥭🥭🥭🥭🥭🥭🥭🥭', '9', ['8', '10', '7'], 'Count them one by one: there are 9.'],
    ['How many ⚽ are here? ⚽⚽⚽⚽⚽⚽', '6', ['5', '7', '8'], 'Count them one by one: there are 6.'],
    ['How many 🐔 are here? 🐔🐔🐔🐔', '4', ['3', '5', '2'], 'Count them: 1, 2, 3, 4.'],
    ['How many 🍌 are here? 🍌🍌🍌🍌🍌🍌🍌🍌', '8', ['7', '9', '6'], 'Count them one by one: there are 8.'],
    ['Which number comes after 9?', '10', ['8', '11', '19'], 'Count on: 9, 10.'],
    ['Which number comes before 15?', '14', ['16', '13', '51'], 'Count: 14, 15.'],
    ['Which number is between 6 and 8?', '7', ['5', '9', '68'], '6, 7, 8.'],
    ['Which number is the biggest?', '21', ['12', '19', '9'], '21 has 2 tens: more than the others.'],
    ['Which number is the smallest?', '3', ['30', '13', '31'], '3 has no tens, so it is the smallest.'],
    ['How do we write “fifteen” in numbers?', '15', ['50', '51', '105'], 'Fifteen is 1 ten and 5 ones: 15.'],
    ['How do we write 12 in words?', 'twelve', ['twenty', 'two', 'eleven'], '12 is twelve.'],
    ['What comes next? 2, 4, 6, 8, …', '10', ['9', '12', '11'], 'Count in twos: add 2 each time.'],
    ['What comes next? 10, 20, 30, …', '40', ['31', '50', '300'], 'Count in tens.'],
    ['What comes next? 20, 19, 18, …', '17', ['19', '21', '16'], 'Count back by 1.'],
    ['What is 0 + 9?', '9', ['0', '90', '10'], 'Adding 0 changes nothing.'],
  ]),
  ...qs('mp', 'Mathematics', 'Place value', [2, 3], [
    ['In 47, what is the value of the 4?', '40', ['4', '7', '47'], 'The 4 is in the tens place: 4 tens = 40.'],
    ['36 is…', '3 tens and 6 ones', ['6 tens and 3 ones', '36 tens', '3 ones and 6 tens'], '36 = 30 + 6.'],
    ['What number is 5 tens and 2 ones?', '52', ['25', '7', '502'], '50 + 2 = 52.'],
    ['Which number is greater than 89?', '98', ['88', '79', '9'], '98 has 9 tens; 89 has only 8 tens.'],
    ['What comes next? 5, 10, 15, 20, …', '25', ['21', '30', '24'], 'Count in fives.'],
  ]),
  ...qs('mh', 'Mathematics', 'Numbers to 1000', [3], [
    ['In 258, which digit is in the hundreds place?', '2', ['5', '8', '25'], '258 = 2 hundreds, 5 tens and 8 ones.'],
    ['What number is 3 hundreds, 4 tens and 1 one?', '341', ['143', '314', '3041'], '300 + 40 + 1 = 341.'],
    ['What is 100 more than 245?', '345', ['255', '246', '445'], 'Add 1 to the hundreds digit: 345.'],
    ['Write “two hundred and six” in numbers.', '206', ['260', '2006', '26'], '200 + 6 = 206.'],
    ['How do we write one thousand in numbers?', '1000', ['100', '10000', '10'], 'One thousand is ten hundreds: 1000.'],
    ['What comes next? 100, 200, 300, …', '400', ['310', '500', '301'], 'Count in hundreds.'],
    ['What comes next? 50, 45, 40, …', '35', ['30', '45', '39'], 'Count back in fives.'],
  ]),
  ...qs('ma', 'Mathematics', 'Addition and subtraction', [1], [
    ['🍊🍊 + 🍊🍊🍊 = ?', '5', ['4', '6', '3'], '2 + 3 = 5.'],
    ['3 + 4 = ?', '7', ['6', '8', '12'], '3 + 4 = 7.'],
    ['6 + 2 = ?', '8', ['9', '4', '7'], '6 + 2 = 8.'],
    ['9 − 4 = ?', '5', ['13', '4', '6'], 'Take 4 from 9: 5 are left.'],
    ['10 − 3 = ?', '7', ['13', '6', '8'], 'Take 3 from 10: 7 are left.'],
    ['Ada has 5 sweets 🍬. She eats 2. How many are left?', '3', ['7', '2', '4'], '5 − 2 = 3.'],
    ['🐟🐟🐟🐟 − 🐟 = ?', '3', ['5', '4', '2'], '4 − 1 = 3.'],
  ]),
  ...qs('mb', 'Mathematics', 'Addition and subtraction', [2, 3], [
    ['8 + 7 = ?', '15', ['14', '16', '1'], '8 + 7 = 15.'],
    ['12 + 6 = ?', '18', ['17', '19', '6'], '12 + 6 = 18.'],
    ['20 − 8 = ?', '12', ['28', '11', '13'], '20 − 8 = 12.'],
    ['25 + 13 = ?', '38', ['37', '12', '48'], '25 + 13 = 38.'],
    ['45 − 21 = ?', '24', ['66', '26', '34'], '45 − 21 = 24.'],
    ['37 + 25 = ?', '62', ['52', '61', '512'], '37 + 25 = 62. Remember to carry the ten.'],
    ['63 − 28 = ?', '35', ['45', '34', '25'], '63 − 28 = 35.'],
    ['Tunde has 14 marbles. Musa gives him 9 more. How many does Tunde have now?', '23', ['5', '22', '24'], '14 + 9 = 23.'],
    ['A bus has 30 people. 12 get down. How many are still on the bus?', '18', ['42', '22', '17'], '30 − 12 = 18.'],
  ]),
  ...qs('mt', 'Mathematics', 'Addition and subtraction', [3], [
    ['124 + 235 = ?', '359', ['369', '349', '111'], '124 + 235 = 359.'],
    ['500 − 200 = ?', '300', ['700', '200', '350'], '5 hundreds − 2 hundreds = 3 hundreds.'],
    ['A school has 150 boys and 140 girls. How many pupils are there?', '290', ['10', '280', '300'], '150 + 140 = 290.'],
  ]),
  ...qs('mx', 'Mathematics', 'Multiplication', [2, 3], [
    ['2 × 3 = ?', '6', ['5', '8', '23'], '3 twos: 2, 4, 6.'],
    ['5 × 4 = ?', '20', ['9', '25', '15'], '4 fives: 5, 10, 15, 20.'],
    ['10 × 6 = ?', '60', ['16', '600', '50'], '6 tens make 60.'],
    ['2 × 8 = ?', '16', ['10', '14', '18'], '8 twos make 16.'],
    ['5 × 7 = ?', '35', ['30', '12', '40'], '7 fives make 35.'],
    ['10 × 10 = ?', '100', ['20', '1000', '110'], '10 tens make 100.'],
    ['🍌🍌 🍌🍌 🍌🍌 3 groups of 2 bananas. How many in all?', '6', ['5', '8', '32'], '3 × 2 = 6.'],
    ['One hand has 5 fingers ✋. How many fingers are on 2 hands?', '10', ['7', '12', '15'], '2 × 5 = 10.'],
  ]),
  ...qs('my', 'Mathematics', 'Multiplication and sharing', [3], [
    ['5 × 9 = ?', '45', ['40', '14', '54'], '9 fives make 45.'],
    ['2 × 12 = ?', '24', ['14', '22', '26'], '12 twos make 24.'],
    ['A table has 4 legs. How many legs do 5 tables have?', '20', ['9', '25', '16'], '5 × 4 = 20.'],
    ['Share 10 oranges equally between 2 children. How many does each child get?', '5', ['8', '12', '20'], '10 ÷ 2 = 5.'],
    ['20 ÷ 5 = ?', '4', ['15', '100', '5'], '4 fives make 20.'],
    ['10 × 7 = ?', '70', ['17', '700', '77'], '7 tens make 70.'],
  ]),
  ...qs('mf', 'Mathematics', 'Fractions', [2, 3], [
    ['What is half of 8?', '4', ['2', '6', '16'], '4 + 4 = 8.'],
    ['What is half of 20?', '10', ['5', '40', '2'], '10 + 10 = 20.'],
    ['A cake is cut into 4 equal parts. Each part is…', 'a quarter', ['a half', 'a third', 'a whole'], '4 equal parts are quarters.'],
    ['A loaf of bread is cut into 2 equal parts. Each part is…', 'a half', ['a quarter', 'a whole', 'a third'], '2 equal parts are halves.'],
    ['How many halves make a whole?', '2', ['1', '4', '3'], '½ + ½ = 1 whole.'],
    ['How many quarters make a whole?', '4', ['2', '3', '8'], '¼ + ¼ + ¼ + ¼ = 1 whole.'],
    ['What is a quarter of 12?', '3', ['4', '6', '8'], 'Share 12 into 4 equal groups: 3 in each.'],
  ]),
  ...qs('ms', 'Mathematics', 'Shapes', [1, 2], [
    ['How many sides does a triangle 🔺 have?', '3', ['4', '2', '5'], 'Tri- means three.'],
    ['Which shape has no corners?', 'Circle', ['Square', 'Triangle', 'Rectangle'], 'A circle is round all the way.'],
    ['How many corners does a square have?', '4', ['3', '5', '6'], 'A square has 4 corners.'],
    ['Which shape has 4 equal sides?', 'Square', ['Triangle', 'Circle', 'Oval'], 'All 4 sides of a square are equal.'],
    ['A door is usually shaped like a…', 'rectangle', ['circle', 'triangle', 'oval'], 'A door has 2 long sides and 2 short sides.'],
  ]),
  ...qs('m3', 'Mathematics', 'Shapes', [2, 3], [
    ['A ball ⚽ is shaped like a…', 'sphere', ['cube', 'cone', 'cylinder'], 'A sphere is round like a ball.'],
    ['A tin of milk is shaped like a…', 'cylinder', ['sphere', 'cube', 'cone'], 'A cylinder has two flat round ends.'],
    ['A dice 🎲 is shaped like a…', 'cube', ['sphere', 'cylinder', 'cone'], 'A cube has 6 square faces.'],
    ['An ice cream cone 🍦 is shaped like a…', 'cone', ['cube', 'cylinder', 'sphere'], 'A cone has a round base and a point.'],
    ['How many faces does a cube have?', '6', ['4', '8', '12'], 'Like a dice: 6 faces.'],
    ['Which shape has 5 sides?', 'Pentagon', ['Hexagon', 'Square', 'Octagon'], 'Penta- means five.'],
  ]),
  ...qs('mm', 'Mathematics', 'Measurement', [1, 2, 3], [
    ['Which is the heaviest?', 'An elephant 🐘', ['A mouse 🐭', 'A cat 🐈', 'A hen 🐔'], 'An elephant is very heavy.'],
    ['Which is the longest?', 'A school bus 🚌', ['A pencil ✏️', 'A spoon 🥄', 'A shoe 👟'], 'A bus is much longer than the others.'],
    ['We measure length with a…', 'ruler', ['clock', 'weighing scale', 'cup'], 'A ruler shows how long something is.'],
    ['We measure how heavy things are with a…', 'weighing scale', ['ruler', 'clock', 'thermometer'], 'A weighing scale measures weight.'],
    ['How many centimetres make 1 metre?', '100', ['10', '1000', '60'], '100 cm = 1 m.'],
    ['We use a clock to tell the…', 'time', ['weight', 'length', 'colour'], 'A clock shows the time.'],
    ['Which is the lightest?', 'A feather 🪶', ['A brick', 'A bag of rice', 'A yam tuber'], 'A feather weighs very little.'],
  ]),
  ...qs('mk', 'Mathematics', 'Time', [1, 2, 3], [
    ['The long hand is on 12 and the short hand is on 3. What time is it?', '3 o’clock', ['12 o’clock', 'half past 3', 'half past 12'], 'Long hand on 12 means o’clock; the short hand shows the hour.'],
    ['The long hand is on 6 and the short hand is between 4 and 5. What time is it?', 'half past 4', ['6 o’clock', '4 o’clock', 'half past 6'], 'Long hand on 6 means half past.'],
    ['How many hours are in one day?', '24', ['12', '7', '60'], 'A day and a night together: 24 hours.'],
    ['How many minutes are in one hour?', '60', ['100', '24', '30'], '1 hour = 60 minutes.'],
    ['Half past 7 is the same as…', '7:30', ['7:15', '6:30', '7:45'], 'Half an hour is 30 minutes.'],
  ]),
  ...qs('md', 'Mathematics', 'Days and months', [1, 2, 3], [
    ['Which day comes after Monday?', 'Tuesday', ['Sunday', 'Wednesday', 'Friday'], 'Monday, then Tuesday.'],
    ['Which day comes before Friday?', 'Thursday', ['Saturday', 'Wednesday', 'Monday'], 'Thursday, then Friday.'],
    ['How many months are in a year?', '12', ['10', '7', '52'], 'January to December: 12 months.'],
    ['Which month comes after March?', 'April', ['May', 'February', 'June'], 'March, then April.'],
    ['Which is the last month of the year?', 'December', ['January', 'November', 'October'], 'December is the 12th month.'],
    ['Which is the first month of the year?', 'January', ['February', 'December', 'June'], 'The year starts in January.'],
    ['Today is Saturday. What day is tomorrow?', 'Sunday', ['Friday', 'Monday', 'Thursday'], 'Saturday, then Sunday.'],
    ['Yesterday was Wednesday. What day is today?', 'Thursday', ['Tuesday', 'Friday', 'Wednesday'], 'Wednesday, then Thursday.'],
  ]),
  ...qs('mn', 'Mathematics', 'Money', [1, 2, 3], [
    ['Which is the most money?', '₦50', ['₦20', '₦10', '₦5'], '50 is the biggest number here.'],
    ['Ngozi buys a pencil for ₦20 and an eraser for ₦10. How much does she pay?', '₦30', ['₦10', '₦20', '₦40'], '₦20 + ₦10 = ₦30.'],
    ['Musa has ₦50. He spends ₦20. How much is left?', '₦30', ['₦70', '₦20', '₦25'], '₦50 − ₦20 = ₦30.'],
    ['How many ₦5 coins make ₦10?', '2', ['5', '10', '3'], '₦5 + ₦5 = ₦10.'],
    ['Two ₦50 notes make…', '₦100', ['₦50', '₦150', '₦500'], '₦50 + ₦50 = ₦100.'],
    ['Bola buys 3 sweets at ₦10 each. How much does she pay?', '₦30', ['₦13', '₦20', '₦40'], '3 × ₦10 = ₦30.'],
    ['Mama gives Aisha ₦100. She buys bread for ₦70. How much change does she get?', '₦30', ['₦170', '₦40', '₦20'], '₦100 − ₦70 = ₦30.'],
  ]),
  ...qs('mq', 'Mathematics', 'Patterns and odd and even numbers', [1, 2, 3], [
    ['What comes next? 🔴🔵🔴🔵🔴 …', '🔵', ['🔴', '🟢', '🟡'], 'Red, blue, red, blue: blue comes next.'],
    ['What comes next? 🍎🍎🍌🍎🍎🍌🍎🍎 …', '🍌', ['🍎', '🍊', '🍇'], 'Two apples, then a banana.'],
    ['What comes next? 1, 3, 5, 7, …', '9', ['8', '10', '11'], 'Add 2 each time: these are odd numbers.'],
    ['Which one is an even number?', '8', ['3', '7', '5'], 'Even numbers end in 0, 2, 4, 6 or 8.'],
    ['Which one is an odd number?', '9', ['4', '10', '6'], 'Odd numbers end in 1, 3, 5, 7 or 9.'],
    ['What comes next? ▲ ■ ▲ ■ ▲ …', '■', ['▲', '●', '★'], 'Triangle, square, triangle, square.'],
  ]),

  // ---------------- English Language
  ...qs('ep', 'English Language', 'Phonics: beginning sounds', [1], [
    ['Which word begins with the sound “b”?', 'ball ⚽', ['cat 🐈', 'dog 🐕', 'sun ☀️'], 'B-all starts with “b”.'],
    ['Which word begins with the sound “m”?', 'mango 🥭', ['yam', 'orange 🍊', 'pawpaw'], 'M-ango starts with “m”.'],
    ['Which word starts with the same sound as “fish” 🐟?', 'fan', ['van', 'pen', 'sun'], 'Fish and fan both start with “f”.'],
    ['🐐 “Goat” begins with which letter?', 'G', ['J', 'C', 'K'], 'G for goat.'],
    ['🐘 “Elephant” begins with which letter?', 'E', ['A', 'L', 'I'], 'E for elephant.'],
    ['Which word begins with a vowel?', 'egg 🥚', ['bag', 'cup', 'hen'], '“Egg” starts with e, a vowel.'],
    ['Which word begins with the “ch” sound?', 'chair 🪑', ['shoe 👟', 'table', 'cup'], 'Ch-air starts with “ch”.'],
  ]),
  ...qs('er', 'English Language', 'Rhyming words', [1, 2], [
    ['Which word rhymes with “cat”?', 'hat', ['cup', 'dog', 'cot'], 'Cat and hat both end in “-at”.'],
    ['Which word rhymes with “sun”?', 'bun', ['sat', 'sin', 'map'], 'Sun and bun both end in “-un”.'],
    ['Which word rhymes with “bed”?', 'red', ['bad', 'bird', 'bat'], 'Bed and red both end in “-ed”.'],
    ['Which word rhymes with “pin”?', 'tin', ['pan', 'pen', 'pot'], 'Pin and tin both end in “-in”.'],
    ['Which word rhymes with “cake”?', 'lake', ['cook', 'cap', 'kite'], 'Cake and lake both end in “-ake”.'],
    ['Which word rhymes with “ball”?', 'wall', ['bell', 'bag', 'bill'], 'Ball and wall both end in “-all”.'],
    ['Which word rhymes with “night”?', 'light', ['note', 'nut', 'late'], 'Night and light both end in “-ight”.'],
  ]),
  ...qs('el', 'English Language', 'Letters of the alphabet', [1, 2], [
    ['How many vowels are in the English alphabet?', '5', ['6', '26', '21'], 'a, e, i, o, u: 5 vowels.'],
    ['How many letters are in the English alphabet?', '26', ['24', '25', '20'], 'A to Z: 26 letters.'],
    ['Which letter comes after “d”?', 'e', ['c', 'f', 'b'], 'a, b, c, d, e.'],
    ['Which letter comes before “m”?', 'l', ['n', 'k', 'o'], 'k, l, m, n.'],
    ['What is the small letter for “B”?', 'b', ['d', 'p', 'q'], 'Big B, small b. Do not mix it up with d.'],
    ['Which word comes first in ABC order?', 'ant', ['boy', 'egg', 'dog'], 'A comes before b, d and e.'],
  ]),
  ...qs('ea', 'English Language', 'A and an', [1, 2], [
    ['I ate ___ orange. 🍊', 'an', ['a', 'am', 'is'], 'Use “an” before a vowel sound: an orange.'],
    ['I saw ___ goat. 🐐', 'a', ['an', 'am', 'at'], 'Use “a” before a consonant sound: a goat.'],
    ['She has ___ egg. 🥚', 'an', ['a', 'am', 'is'], 'Egg starts with a vowel: an egg.'],
    ['There is ___ umbrella by the door. ☂️', 'an', ['a', 'am', 'as'], 'Umbrella starts with a vowel: an umbrella.'],
    ['Emeka has ___ bicycle. 🚲', 'a', ['an', 'am', 'is'], 'Bicycle starts with b: a bicycle.'],
  ]),
  ...qs('es', 'English Language', 'Plurals', [1, 2, 3], [
    ['One cat, two ___', 'cats', ['cat', 'cates', 'catss'], 'Add -s: cats.'],
    ['One box, two ___', 'boxes', ['boxs', 'box', 'boxies'], 'Words ending in x add -es: boxes.'],
    ['One baby, two ___', 'babies', ['babys', 'babyes', 'baby'], 'Change y to i and add -es: babies.'],
    ['One child, many ___', 'children', ['childs', 'childrens', 'childes'], 'Child becomes children.'],
    ['One foot, two ___', 'feet', ['foots', 'feets', 'footes'], 'Foot becomes feet.'],
    ['One man, two ___', 'men', ['mans', 'mens', 'manes'], 'Man becomes men.'],
  ]),
  ...qs('eo', 'English Language', 'Opposites', [1, 2, 3], [
    ['What is the opposite of “tall”?', 'short', ['long', 'big', 'high'], 'Tall and short are opposites.'],
    ['What is the opposite of “clean”?', 'dirty', ['neat', 'wet', 'fresh'], 'Clean and dirty are opposites.'],
    ['What is the opposite of “come”?', 'go', ['run', 'sit', 'stop'], 'Come and go are opposites.'],
    ['What is the opposite of “rich”?', 'poor', ['strong', 'old', 'tall'], 'Rich and poor are opposites.'],
    ['What is the opposite of “first”?', 'last', ['second', 'next', 'early'], 'First and last are opposites.'],
    ['What is the opposite of “heavy”?', 'light', ['big', 'hard', 'thick'], 'Heavy and light are opposites.'],
  ]),
  ...qs('ev', 'English Language', 'Verbs (action words)', [1, 2, 3], [
    ['Which is an action word?', 'jump', ['table', 'red', 'bag'], 'Jump is something we do.'],
    ['The bird can ___. 🐦', 'fly', ['sky', 'nest', 'wing'], 'Fly is the action word.'],
    ['Musa ___ water every day.', 'drinks', ['drink', 'drinking', 'drinked'], 'Musa drinks: one person, so add -s.'],
    ['I ___ a boy.', 'am', ['is', 'are', 'be'], 'We say “I am”.'],
    ['They ___ playing football. ⚽', 'are', ['is', 'am', 'was'], 'We say “they are”.'],
    ['Yesterday I ___ to the market.', 'went', ['go', 'goes', 'going'], 'Yesterday is the past, so “went”.'],
    ['Kemi is ___ a song. 🎵', 'singing', ['sing', 'sings', 'sang'], 'After “is”, use the -ing word: singing.'],
  ]),
  ...qs('eg', 'English Language', 'Nouns, pronouns and describing words', [1, 2, 3], [
    ['Which is a naming word?', 'teacher', ['run', 'tall', 'quickly'], 'A naming word (noun) names a person, place or thing.'],
    ['In “the red ball”, which word tells the colour?', 'red', ['the', 'ball', 'a'], 'Red describes the ball.'],
    ['Ada is my sister. ___ is kind.', 'She', ['He', 'It', 'They'], 'Ada is a girl, so we use “she”.'],
    ['Tunde is my brother. ___ likes football.', 'He', ['She', 'It', 'We'], 'Tunde is a boy, so we use “he”.'],
    ['Which word means the same as “small”?', 'little', ['big', 'huge', 'tall'], 'Small and little mean the same.'],
    ['big, bigger, ___', 'biggest', ['bigest', 'more big', 'bigst'], 'Double the g: biggest.'],
  ]),
  ...qs('ec', 'English Language', 'Capital letters and punctuation', [1, 2, 3], [
    ['In “i like rice”, which word should have a capital letter?', 'i', ['like', 'rice', 'none'], 'When “I” means me, it is always a capital letter.'],
    ['What mark ends a telling sentence?', 'a full stop (.)', ['a question mark (?)', 'a comma (,)', 'an exclamation mark (!)'], 'A telling sentence ends with a full stop.'],
    ['“What is your name” needs which mark at the end?', 'a question mark (?)', ['a full stop (.)', 'a comma (,)', 'an apostrophe (’)'], 'Questions end with a question mark.'],
    ['Which word needs a capital letter?', 'Lagos', ['city', 'market', 'river'], 'Names of places start with a capital letter.'],
  ]),
  ...qs('ed', 'English Language', 'Spelling days and months', [2, 3], [
    ['Which day is spelt correctly?', 'Thursday', ['Thurday', 'Thusday', 'Tursday'], 'T-h-u-r-s-d-a-y.'],
    ['Which month is spelt correctly?', 'January', ['Janury', 'Janaury', 'Jenuary'], 'J-a-n-u-a-r-y.'],
    ['Which day is spelt correctly?', 'Saturday', ['Saterday', 'Satuday', 'Sartuday'], 'S-a-t-u-r-d-a-y.'],
    ['Which month is spelt correctly?', 'August', ['Augost', 'Agust', 'Augus'], 'A-u-g-u-s-t.'],
  ]),

  // ---------------- Basic Science
  ...qs('sb', 'Basic Science', 'Our body and senses', [1, 2, 3], [
    ['We see with our…', 'eyes 👀', ['ears 👂', 'nose 👃', 'hands ✋'], 'Eyes are for seeing.'],
    ['We hear with our…', 'ears 👂', ['eyes 👀', 'mouth 👄', 'feet 🦶'], 'Ears are for hearing.'],
    ['We taste food with our…', 'tongue 👅', ['nose 👃', 'ears 👂', 'hair'], 'The tongue tastes food.'],
    ['We feel hot and cold with our…', 'skin', ['hair', 'teeth', 'eyes'], 'The skin feels touch, hot and cold.'],
    ['How many senses do we have?', '5', ['3', '7', '10'], 'Sight, hearing, smell, taste and touch.'],
    ['How many fingers are on one hand? ✋', '5', ['4', '6', '10'], 'Count them: 5 fingers.'],
    ['Which body part do we use to walk?', 'legs', ['arms', 'ears', 'neck'], 'We walk with our legs.'],
    ['Where is the brain?', 'In the head', ['In the chest', 'In the stomach', 'In the leg'], 'The skull in our head protects the brain.'],
    ['We chew food with our…', 'teeth 🦷', ['lips', 'nose', 'ears'], 'Teeth bite and chew food.'],
    ['What holds our body up and gives it shape?', 'bones', ['hair', 'nails', 'blood'], 'Our bones make up the skeleton.'],
  ]),
  ...qs('sh', 'Basic Science', 'Animals and their homes', [1, 2, 3], [
    ['Where does a bird live? 🐦', 'In a nest', ['In a hive', 'In a kennel', 'In a stable'], 'Birds build nests.'],
    ['Where do bees live? 🐝', 'In a hive', ['In a stable', 'In a kennel', 'In a pond'], 'Bees live in a hive.'],
    ['A spider lives in a…', 'web 🕸️', ['hive', 'stable', 'kennel'], 'A spider spins a web.'],
    ['A horse lives in a…', 'stable', ['hive', 'web', 'nest'], 'Horses are kept in a stable.'],
    ['A dog’s house is called a…', 'kennel', ['hive', 'web', 'stable'], 'A kennel is a house for a dog.'],
    ['A lion’s home is called a…', 'den', ['hive', 'nest', 'web'], 'Lions rest in a den.'],
    ['A fish lives in…', 'water', ['a tree', 'a nest', 'a stable'], 'Fish live in rivers, ponds and the sea.'],
  ]),
  ...qs('sa', 'Basic Science', 'Animals', [1, 2, 3], [
    ['A baby hen is called a…', 'chick 🐥', ['calf', 'kid', 'puppy'], 'A hen’s young one is a chick.'],
    ['Which farm animal gives us milk to drink?', 'Cow 🐄', ['Hen', 'Duck', 'Turkey'], 'Cows give us milk.'],
    ['Which animal lays the eggs we eat?', 'Hen 🐔', ['Goat', 'Cow', 'Dog'], 'Hens lay eggs.'],
    ['What does a cow eat?', 'Grass', ['Meat', 'Fish', 'Stones'], 'Cows eat grass.'],
    ['Which animal eats meat?', 'Lion 🦁', ['Cow', 'Goat', 'Sheep'], 'Lions hunt other animals for food.'],
    ['Which animal can fly?', 'Eagle 🦅', ['Dog', 'Cow', 'Snail'], 'An eagle has wings.'],
    ['Which animal has no legs?', 'Snake 🐍', ['Dog', 'Hen', 'Goat'], 'A snake slides on its belly.'],
    ['Which animal has feathers?', 'Hen 🐔', ['Goat', 'Cat', 'Fish'], 'Birds have feathers.'],
    ['Which animal lives in water?', 'Fish 🐟', ['Goat', 'Hen', 'Cat'], 'Fish live in water.'],
    ['What helps a fish to swim?', 'Fins', ['Legs', 'Wings', 'Horns'], 'A fish moves with its fins and tail.'],
    ['Which is a wild animal?', 'Lion 🦁', ['Goat', 'Hen', 'Cat'], 'Lions live in the wild, not at home.'],
  ]),
  ...qs('sp', 'Basic Science', 'Plants and living things', [1, 2, 3], [
    ['Which part of a plant is usually green and flat?', 'The leaf 🍃', ['The root', 'The seed', 'The bark'], 'Most leaves are green and flat.'],
    ['Plants need ___ to grow.', 'water 💧', ['sweets', 'salt', 'oil'], 'Plants need water, air and sunlight.'],
    ['A seed grows into a…', 'plant 🌱', ['stone', 'cloud', 'rock'], 'Plant a seed and it grows.'],
    ['Which of these is a fruit?', 'Orange 🍊', ['Yam', 'Carrot', 'Cassava'], 'An orange is a fruit.'],
    ['Which of these is a vegetable?', 'Spinach', ['Mango', 'Banana', 'Orange'], 'Spinach is a green leafy vegetable.'],
    ['Which is a living thing?', 'A tree 🌳', ['A stone', 'A chair', 'A car'], 'A tree grows and needs water.'],
    ['Which is a non-living thing?', 'A stone 🪨', ['A goat', 'A boy', 'A tree'], 'A stone does not grow or breathe.'],
    ['Living things need ___ to breathe.', 'air', ['sand', 'stones', 'paper'], 'We breathe in air.'],
  ]),
  ...qs('sw', 'Basic Science', 'Weather and seasons', [1, 2, 3], [
    ['When does it rain the most in Nigeria?', 'In the rainy season', ['In the dry season', 'During harmattan', 'In December'], 'Most rain falls in the rainy season.'],
    ['The cold, dry and dusty wind in the dry season is called…', 'harmattan', ['rainbow', 'flood', 'thunder'], 'The harmattan blows from the Sahara Desert.'],
    ['Harmattan comes in which season?', 'The dry season', ['The rainy season', 'Spring', 'Autumn'], 'Harmattan comes in the dry season.'],
    ['What do we use to keep dry in the rain?', 'An umbrella ☂️', ['Sunglasses', 'A fan', 'A pillow'], 'An umbrella keeps rain off us.'],
    ['Which tells us that rain may soon fall?', 'Dark clouds 🌧️', ['A bright sun', 'A clear blue sky', 'Dry dust'], 'Dark clouds often bring rain.'],
    ['The sun gives us light and…', 'heat', ['rain', 'ice', 'sand'], 'The sun warms the earth.'],
  ]),
  ...qs('sx', 'Basic Science', 'Water', [2, 3], [
    ['Water turns into ice when it is very…', 'cold', ['hot', 'dirty', 'sweet'], 'Water freezes when it is very cold.'],
    ['When water is boiled it gives off…', 'steam', ['ice', 'sand', 'oil'], 'Hot water turns into steam.'],
    ['Which water is safe to drink?', 'Clean, boiled water', ['Water from a gutter', 'Flood water', 'Dirty pond water'], 'Boiling kills germs in water.'],
  ]),
  ...qs('sf', 'Basic Science', 'Health, hygiene and safety', [1, 2, 3], [
    ['Which food helps us to grow strong?', 'Beans', ['Sweets', 'Fizzy drinks', 'Chewing gum'], 'Beans give us protein to grow.'],
    ['Which snack is the healthiest?', 'A banana 🍌', ['A lollipop 🍭', 'A fizzy drink', 'A doughnut 🍩'], 'Fruit is a healthy snack.'],
    ['How often should we brush our teeth?', 'Morning and night', ['Once a week', 'Once a month', 'Never'], 'Brush twice a day to keep teeth clean.'],
    ['When should we wash our hands?', 'Before eating', ['Only at night', 'Once a week', 'Never'], 'Washing hands removes germs from food.'],
    ['How often should we take a bath?', 'Every day', ['Once a week', 'Once a month', 'Never'], 'Bathing every day keeps our body clean.'],
    ['What keeps mosquitoes off us while we sleep?', 'A mosquito net', ['A pillow', 'A toy', 'A cup'], 'A net stops mosquito bites.'],
    ['Where should we put rubbish?', 'In a dustbin 🗑️', ['On the road', 'On the classroom floor', 'In the gutter'], 'Rubbish belongs in a dustbin.'],
    ['Which of these must children NOT play with?', 'Matches', ['A ball', 'A doll', 'A skipping rope'], 'Matches can start a fire.'],
    ['You see a broken electric wire. What should you do?', 'Keep away and tell an adult', ['Touch it', 'Play with it', 'Pull it'], 'Electric wires can kill. Stay away.'],
    ['Eating too many sweets can damage our…', 'teeth', ['hair', 'ears', 'legs'], 'Sugar can make holes in teeth.'],
  ]),

  // ---------------- Social Studies
  ...qs('xf', 'Social Studies', 'The family', [1, 2, 3], [
    ['Who takes care of children at home?', 'Parents', ['Strangers', 'Visitors', 'Robbers'], 'Parents love and care for their children.'],
    ['Your father’s mother is your…', 'grandmother', ['aunt', 'sister', 'cousin'], 'Your parents’ mothers are your grandmothers.'],
    ['Your mother’s brother is your…', 'uncle', ['cousin', 'grandfather', 'nephew'], 'Your parents’ brothers are your uncles.'],
    ['A son of your parents (not you) is your…', 'brother', ['uncle', 'cousin', 'father'], 'Boys with the same parents as you are your brothers.'],
  ]),
  ...qs('xs', 'Social Studies', 'The school', [1, 2, 3], [
    ['Who teaches pupils in school?', 'The teacher', ['The driver', 'The farmer', 'The tailor'], 'Teachers help us learn.'],
    ['Who is the head of a primary school?', 'The head teacher', ['The class captain', 'The cook', 'The driver'], 'The head teacher leads the school.'],
    ['We should come to school…', 'on time', ['late', 'dirty', 'without our books'], 'Being on time is a good habit.'],
    ['Who should keep our classroom clean?', 'All of us', ['Only the teacher', 'Only the head teacher', 'Nobody'], 'Everyone helps to keep the class clean.'],
    ['Which is a place of learning?', 'School 🏫', ['Market', 'Motor park', 'Bank'], 'We go to school to learn.'],
  ]),
  ...qs('xh', 'Social Studies', 'Community helpers', [1, 2, 3], [
    ['Who treats sick people?', 'Doctor 🩺', ['Carpenter', 'Tailor', 'Farmer'], 'Doctors help sick people get well.'],
    ['Who sews clothes?', 'Tailor 🧵', ['Mechanic', 'Nurse', 'Barber'], 'A tailor sews clothes.'],
    ['Who cuts hair?', 'Barber 💈', ['Tailor', 'Baker', 'Pilot'], 'A barber cuts hair.'],
    ['Who grows crops like yam and maize?', 'Farmer 🧑‍🌾', ['Driver', 'Police officer', 'Teacher'], 'Farmers grow our food.'],
    ['Who puts out fires?', 'Firefighter 🚒', ['Nurse', 'Tailor', 'Trader'], 'Firefighters stop fires.'],
    ['Who flies an aeroplane?', 'Pilot ✈️', ['Driver', 'Sailor', 'Farmer'], 'A pilot flies aeroplanes.'],
    ['Who repairs cars?', 'Mechanic 🔧', ['Baker', 'Carpenter', 'Doctor'], 'A mechanic fixes cars.'],
    ['Who makes chairs and tables from wood?', 'Carpenter 🪚', ['Mechanic', 'Cobbler', 'Tailor'], 'A carpenter works with wood.'],
    ['Who mends shoes?', 'Cobbler 👞', ['Carpenter', 'Tailor', 'Barber'], 'A cobbler mends shoes.'],
    ['Who bakes bread?', 'Baker 🍞', ['Barber', 'Pilot', 'Nurse'], 'A baker bakes bread.'],
    ['Police officers help to keep us…', 'safe', ['hungry', 'sick', 'dirty'], 'The police protect people.'],
  ]),
  ...qs('xp', 'Social Studies', 'Places in our community', [1, 2], [
    ['Where do we buy food like rice and tomatoes?', 'Market', ['School', 'Police station', 'Bank'], 'People buy and sell at the market.'],
    ['Where do we go when we are very sick?', 'Hospital 🏥', ['Market', 'Motor park', 'Playground'], 'Doctors and nurses work in hospitals.'],
    ['Where should children play?', 'In the playground', ['On the road', 'In the gutter', 'On the expressway'], 'The playground is safe for play.'],
  ]),

  // ---------------- Civic Education
  ...qs('cn', 'Civic Education', 'National symbols', [2, 3], [
    ['How many bands (stripes) does the Nigerian flag have?', '3', ['2', '4', '5'], 'Green, white, green: 3 bands.'],
    ['What colour is the middle band of the Nigerian flag?', 'White', ['Green', 'Red', 'Blue'], 'The middle band is white.'],
    ['The white on the Nigerian flag stands for…', 'peace', ['farming', 'the sky', 'money'], 'White stands for peace and unity.'],
    ['The green on the Nigerian flag stands for…', 'farming (agriculture)', ['peace', 'water', 'the sky'], 'Green stands for Nigeria’s rich land and farming.'],
    ['Who designed the Nigerian flag?', 'Taiwo Akinkunmi', ['Nnamdi Azikiwe', 'Herbert Macaulay', 'Ahmadu Bello'], 'Taiwo Akinkunmi designed it when he was a student.'],
    ['Which bird is on Nigeria’s coat of arms?', 'Eagle 🦅', ['Parrot', 'Owl', 'Hen'], 'A red eagle stands on top.'],
    ['Which animals are on Nigeria’s coat of arms?', 'Two horses', ['Two lions', 'Two elephants', 'Two goats'], 'Two white horses hold up the shield.'],
    ['Nigeria’s money is called the…', 'naira', ['dollar', 'pound', 'cedi'], 'We spend naira (₦).'],
    ['Nigeria’s Independence Day is on…', '1 October', ['1 January', '25 December', '12 June'], 'Nigeria became independent on 1 October 1960.'],
    ['When the National Anthem is sung, we should…', 'stand still', ['sit and talk', 'run around', 'eat'], 'We stand still to show respect.'],
  ]),
  ...qs('cm', 'Civic Education', 'Good manners', [1, 2, 3], [
    ['When someone gives you a gift, you say…', 'Thank you', ['Sorry', 'Go away', 'Goodbye'], 'Always say thank you.'],
    ['When you hurt someone by mistake, you say…', 'Sorry', ['Thank you', 'Hello', 'Well done'], 'Saying sorry is good manners.'],
    ['When you ask for something, you say…', 'Please', ['Sorry', 'Goodbye', 'Go away'], 'Please is a magic word.'],
    ['How should we greet elders?', 'With respect', ['By shouting', 'By ignoring them', 'By laughing at them'], 'We greet elders politely.'],
    ['A stranger offers you sweets and a ride. What should you do?', 'Say no and tell a trusted adult', ['Take the sweets', 'Follow the stranger', 'Get into the car'], 'Never go with a stranger.'],
  ]),
  ...qs('cr', 'Civic Education', 'Road safety', [1, 2, 3], [
    ['What does a red traffic light 🔴 mean?', 'Stop', ['Go', 'Speed up', 'Turn round'], 'Red means stop.'],
    ['What does a green traffic light 🟢 mean?', 'Go', ['Stop', 'Get ready', 'Turn back'], 'Green means go.'],
    ['Where is the safest place to cross the road?', 'At a zebra crossing', ['At a bend', 'Between parked cars', 'Anywhere'], 'Cross at a zebra crossing.'],
    ['Before you cross the road, you should look…', 'left and right', ['only up', 'only down', 'at your shoes'], 'Look both ways for cars.'],
    ['In a car, children should…', 'wear a seat belt', ['stand up', 'put their hands out of the window', 'sit on the driver’s lap'], 'A seat belt keeps us safe.'],
  ]),

  // ---------------- Verbal Reasoning
  ...qs('vo', 'Verbal Reasoning', 'Odd one out', [1, 2, 3], [
    ['Which is the odd one out?', 'mango 🥭', ['dog 🐕', 'cat 🐈', 'goat 🐐'], 'A mango is a fruit; the others are animals.'],
    ['Which is the odd one out?', 'chair', ['red', 'blue', 'green'], 'Red, blue and green are colours.'],
    ['Which is the odd one out?', 'spoon', ['orange', 'banana', 'mango'], 'The others are fruits.'],
    ['Which number is the odd one out: 2, 4, 6, 7?', '7', ['2', '4', '6'], '7 is odd; the others are even.'],
    ['Which is the odd one out?', 'yam', ['car', 'bus', 'lorry'], 'Car, bus and lorry are vehicles.'],
    ['Which is the odd one out?', 'bread', ['shirt', 'skirt', 'trousers'], 'The others are clothes.'],
    ['Which is the odd one out?', 'March', ['Monday', 'Friday', 'Sunday'], 'March is a month; the others are days.'],
    ['Which is the odd one out?', 'cup', ['eye', 'ear', 'nose'], 'Eye, ear and nose are parts of the body.'],
    ['Which is the odd one out?', 'cow', ['hen', 'duck', 'eagle'], 'Hen, duck and eagle are birds.'],
    ['Which is the odd one out?', 'ball', ['knife', 'spoon', 'fork'], 'Knife, spoon and fork are for eating.'],
    ['Which word does not belong?', 'sad', ['happy', 'glad', 'joyful'], 'Happy, glad and joyful mean the same.'],
  ]),
  ...qs('vn', 'Verbal Reasoning', 'What comes next', [1, 2, 3], [
    ['What comes next? A, B, C, …', 'D', ['E', 'F', 'B'], 'The alphabet: A, B, C, D.'],
    ['What comes next? A, C, E, …', 'G', ['F', 'H', 'D'], 'Skip one letter each time.'],
    ['What comes next? Mon, Tue, Wed, …', 'Thu', ['Fri', 'Sat', 'Sun'], 'Wednesday, then Thursday.'],
    ['What comes next? 1, 2, 3, 1, 2, 3, 1, …', '2', ['3', '1', '4'], 'The pattern 1, 2, 3 repeats.'],
  ]),
  ...qs('va', 'Verbal Reasoning', 'Word pairs', [2, 3], [
    ['Bird is to nest as bee is to…', 'hive', ['web', 'den', 'kennel'], 'A bird lives in a nest; a bee lives in a hive.'],
    ['Day is to night as hot is to…', 'cold', ['sun', 'warm', 'fire'], 'They are opposites.'],
    ['Puppy is to dog as kitten is to…', 'cat', ['rat', 'hen', 'goat'], 'A kitten is a young cat.'],
    ['Hand is to glove as head is to…', 'hat', ['sock', 'belt', 'ring'], 'A glove goes on a hand; a hat goes on a head.'],
  ]),
];

// ------------------------------------------------------------ spelling words

export const LOWER_PRIMARY_WORDS: GameWord[] = [
  ...ws([1], undefined, [
    ['cat', 'a small furry pet', 'The cat drinks milk.'],
    ['dog', 'a pet that barks', 'Our dog barks at night.'],
    ['hen', 'a bird that lays eggs', 'The hen sat on her eggs.'],
    ['sun', 'it shines in the sky by day', 'The sun is very hot today.'],
    ['bag', 'we carry books in it', 'Put your book in your bag.'],
    ['cup', 'we drink from it', 'Ngozi drank tea from a cup.'],
    ['pen', 'we write with it', 'Write your name with a pen.'],
    ['bed', 'we sleep on it', 'I go to bed at eight o’clock.'],
    ['red', 'the colour of a ripe tomato', 'Musa has a red ball.'],
    ['big', 'large', 'An elephant is a big animal.'],
    ['run', 'to move fast on your feet', 'We run in the playground.'],
    ['sit', 'to rest on a chair', 'Please sit on your chair.'],
    ['box', 'a container with straight sides', 'The chalk is in the box.'],
    ['egg', 'a hen lays it', 'Mama fried an egg for me.'],
    ['fan', 'it blows cool air', 'Switch on the fan, please.'],
    ['yam', 'a big root crop we eat', 'We ate yam and egg sauce.'],
    ['bus', 'a big vehicle for many people', 'We went to Ibadan by bus.'],
    ['map', 'a drawing of a place', 'Find Kano on the map.'],
    ['fish', 'it lives and swims in water', 'The fish swims in the river.'],
    ['book', 'pages we read', 'Open your book to page two.'],
    ['ball', 'a round thing we play with', 'Kick the ball to Tunde.'],
    ['tree', 'a big plant with a trunk', 'The mango tree is tall.'],
    ['milk', 'a white drink from cows', 'I drink milk in the morning.'],
    ['hand', 'it has five fingers', 'Raise your hand to answer.'],
    ['goat', 'a farm animal that bleats', 'The goat is eating grass.'],
    ['rain', 'water falling from clouds', 'The rain is falling hard.'],
    ['one', 'the number 1', 'I have one nose.'],
    ['two', 'the number 2', 'I have two eyes.'],
  ]),
  ...ws([1, 2], undefined, [
    ['three', 'the number 3', 'A triangle has three sides.'],
    ['four', 'the number 4', 'A goat has four legs.'],
    ['eight', 'the number 8', 'An octagon has eight sides.'],
    ['green', 'the colour of leaves', 'Our flag is green and white.'],
    ['white', 'the colour of milk', 'Chalk is white.'],
    ['yellow', 'the colour of a ripe banana', 'The ripe banana is yellow.'],
    ['mother', 'your mum', 'My mother cooks jollof rice.'],
    ['father', 'your dad', 'My father is a farmer.'],
    ['sister', 'a girl with the same parents as you', 'My sister is called Aisha.'],
    ['brother', 'a boy with the same parents as you', 'My brother is called Emeka.'],
    ['house', 'a building we live in', 'Our house has a blue door.'],
    ['water', 'a clear liquid we drink', 'Drink clean water every day.'],
    ['chair', 'we sit on it', 'Push your chair under the table.'],
    ['table', 'furniture with a flat top and legs', 'Put the plates on the table.'],
    ['mango', 'a sweet yellow fruit', 'This mango is very sweet.'],
    ['orange', 'a round juicy fruit', 'Tolu peeled an orange.'],
    ['banana', 'a long yellow fruit', 'I ate a banana after school.'],
    ['said', 'spoke', 'Ada said, “Good morning.”'],
    ['they', 'those people', 'Look, they are playing football.'],
    ['was', 'past of “is”', 'It was hot yesterday.'],
    ['come', 'to move towards here', 'Please come here.'],
    ['some', 'a few', 'Give me some groundnuts.'],
    ['what', 'used to ask about a thing', 'Tell me what your name is.'],
    ['where', 'in what place', 'I do not know where my pencil is.'],
    ['there', 'in that place', 'Put the bag over there.'],
    ['have', 'to own or hold', 'I have a new pencil.'],
    ['nose', 'we smell with it', 'I smell food with my nose.'],
    ['mouth', 'we eat and talk with it', 'Cover your mouth when you cough.'],
    ['teeth', 'we chew food with them', 'Brush your teeth every night.'],
    ['ear', 'we hear with it', 'Whisper in my ear.'],
    ['seed', 'a new plant grows from it', 'Plant the maize seed in the soil.'],
    ['cloud', 'it floats in the sky and brings rain', 'A dark cloud covered the sun.'],
    ['flag', 'a cloth with a country’s colours', 'We salute the flag every morning.'],
  ]),
  ...ws([2, 3], undefined, [
    ['does', 'a form of “do”', 'Musa does his homework every day.'],
    ['could', 'was able to', 'Chiamaka could read at five.'],
    ['would', 'a word for what might happen', 'I would like some water, please.'],
    ['eleven', 'the number 11', 'A football team has eleven players.'],
    ['twelve', 'the number 12', 'A year has twelve months.'],
    ['twenty', 'the number 20', 'There are twenty pupils in my class.'],
    ['purple', 'a colour made from red and blue', 'Grace has a purple dress.'],
    ['teacher', 'a person who teaches', 'Our teacher reads us stories.'],
    ['doctor', 'a person who treats sick people', 'The doctor gave me medicine.'],
    ['farmer', 'a person who grows crops', 'The farmer grows cassava.'],
    ['tailor', 'a person who sews clothes', 'The tailor sewed my uniform.'],
    ['market', 'a place to buy and sell', 'We buy tomatoes at the market.'],
    ['Monday', 'the day after Sunday', 'School starts on Monday.'],
    ['Tuesday', 'the day after Monday', 'We have art on Tuesday.'],
    ['Thursday', 'the day after Wednesday', 'Thursday is our library day.'],
    ['Friday', 'the day after Thursday', 'We wear our house colours on Friday.'],
    ['Saturday', 'the day after Friday', 'We wash clothes on Saturday.'],
    ['Sunday', 'the day after Saturday', 'Grandma visits us on Sunday.'],
    ['January', 'the first month of the year', 'School resumes in January.'],
    ['March', 'the third month of the year', 'My birthday is in March.'],
    ['April', 'the fourth month of the year', 'The rain starts in April.'],
    ['August', 'the eighth month of the year', 'We go on holiday in August.'],
    ['October', 'the tenth month of the year', 'Independence Day is in October.'],
    ['December', 'the last month of the year', 'Harmattan blows in December.'],
    ['circle', 'a round flat shape', 'Draw a circle on the board.'],
    ['square', 'a shape with four equal sides', 'The window is a square.'],
    ['half', 'one of two equal parts', 'Give your sister half of the orange.'],
    ['money', 'what we use to buy things', 'Keep your money in your purse.'],
    ['plant', 'a living thing that grows in soil', 'Water the plant every day.'],
    ['weather', 'how hot, cold, wet or dry it is', 'The weather is cold this morning.'],
    ['healthy', 'well and strong', 'Fruits keep us healthy.'],
    ['please', 'a polite word when asking', 'Say please when you ask for something.'],
    ['thank', 'to show you are grateful', 'Always thank people who help you.'],
    ['sorry', 'a word we say after a mistake', 'Bayo said he was sorry.'],
  ]),
];
