import type { CuratedQuestion, GameWord, MatchPack, TrueFalseFact } from '../games-content';
import type { GameLevel } from '../games';

/**
 * EduGames content for UPPER PRIMARY: Primary 4–6 (ages 9–11), including
 * Common Entrance (NCEE) preparation. NERDC Basic Education curriculum,
 * Nigerian context, British spelling. Every item is checked; ids are stable.
 *
 * Quiz questions list the right answer first (`a`) and three wrong ones (`w`).
 */

const LEVEL: GameLevel = 'PRIMARY';

/** Primary 4–6. */
const ALL = [4, 5, 6];
/** Primary 4–5. */
const LOW = [4, 5];
/** Primary 5–6. */
const HIGH = [5, 6];
/** Primary 6 (and Common Entrance). */
const P6 = [6];

type QRow = [q: string, a: string, w: [string, string, string], topic: string, years: number[], explain?: string];
type FRow = [statement: string, answer: boolean, explain: string, topic: string, years: number[]];
type WRow = [word: string, meaning: string, sentence: string, years: number[], subject?: string];

const mcq = (prefix: string, subject: string, rows: QRow[]): CuratedQuestion[] =>
  rows.map(([q, a, w, topic, years, explain], i) => ({ id: `up-q-${prefix}${i + 1}`, level: LEVEL, subject, topic, q, a, w, explain, years }));

const tf = (prefix: string, subject: string, rows: FRow[]): TrueFalseFact[] =>
  rows.map(([statement, answer, explain, topic, years], i) => ({ id: `up-tf-${prefix}${i + 1}`, level: LEVEL, subject, topic, statement, answer, explain, years }));

const words = (rows: WRow[]): GameWord[] =>
  rows.map(([word, meaning, sentence, years, subject]) => ({ word, level: LEVEL, meaning, sentence, subject, years }));

// ------------------------------------------------------------ match packs

export const UPPER_PRIMARY_MATCH_PACKS: MatchPack[] = [
  {
    id: 'up-synonyms',
    title: 'Synonyms: same meaning',
    subject: 'English Language',
    levels: ['PRIMARY'],
    leftLabel: 'Word',
    rightLabel: 'Synonym',
    years: ALL,
    pairs: [
      ['Begin', 'Start'],
      ['Huge', 'Enormous'],
      ['Brave', 'Courageous'],
      ['Rapid', 'Fast'],
      ['Glad', 'Joyful'],
      ['Tiny', 'Little'],
      ['Shut', 'Close'],
      ['Purchase', 'Buy'],
      ['Reply', 'Answer'],
      ['Assist', 'Help'],
      ['Silent', 'Quiet'],
      ['Wealthy', 'Rich'],
      ['Ill', 'Sick'],
      ['Gift', 'Present'],
      ['Choose', 'Select'],
    ],
  },
  {
    id: 'up-antonyms',
    title: 'Antonyms: opposite meaning',
    subject: 'English Language',
    levels: ['PRIMARY'],
    leftLabel: 'Word',
    rightLabel: 'Antonym',
    years: ALL,
    pairs: [
      ['Ancient', 'Modern'],
      ['Generous', 'Stingy'],
      ['Accept', 'Refuse'],
      ['Expensive', 'Cheap'],
      ['Victory', 'Defeat'],
      ['Arrive', 'Depart'],
      ['Strong', 'Weak'],
      ['Brave', 'Cowardly'],
      ['Rough', 'Smooth'],
      ['Increase', 'Decrease'],
      ['Friend', 'Enemy'],
      ['Polite', 'Rude'],
      ['Remember', 'Forget'],
      ['Borrow', 'Lend'],
    ],
  },
  {
    id: 'up-plurals',
    title: 'Tricky plurals',
    subject: 'English Language',
    levels: ['PRIMARY'],
    leftLabel: 'Singular',
    rightLabel: 'Plural',
    years: LOW,
    pairs: [
      ['Child', 'Children'],
      ['Knife', 'Knives'],
      ['Mouse', 'Mice'],
      ['Tooth', 'Teeth'],
      ['Foot', 'Feet'],
      ['Woman', 'Women'],
      ['Potato', 'Potatoes'],
      ['Baby', 'Babies'],
      ['Box', 'Boxes'],
      ['Leaf', 'Leaves'],
      ['Goose', 'Geese'],
      ['Ox', 'Oxen'],
      ['Wife', 'Wives'],
      ['Church', 'Churches'],
      ['Lady', 'Ladies'],
    ],
  },
  {
    id: 'up-west-africa-capitals',
    title: 'West Africa and neighbours: capitals',
    subject: 'Social Studies',
    levels: ['PRIMARY'],
    leftLabel: 'Country',
    rightLabel: 'Capital',
    years: HIGH,
    pairs: [
      ['Nigeria', 'Abuja'],
      ['Ghana', 'Accra'],
      ['Benin Republic', 'Porto-Novo'],
      ['Togo', 'Lomé'],
      ['Niger', 'Niamey'],
      ['Senegal', 'Dakar'],
      ['Mali', 'Bamako'],
      ['Burkina Faso', 'Ouagadougou'],
      ['Côte d’Ivoire', 'Yamoussoukro'],
      ['Liberia', 'Monrovia'],
      ['Sierra Leone', 'Freetown'],
      ['Guinea', 'Conakry'],
      ['The Gambia', 'Banjul'],
      ['Cameroon', 'Yaoundé'],
      ['Chad', 'N’Djamena'],
    ],
  },
  {
    id: 'up-unit-conversions',
    title: 'Units and what they equal',
    subject: 'Mathematics',
    levels: ['PRIMARY'],
    leftLabel: 'Unit',
    rightLabel: 'Equals',
    years: ALL,
    pairs: [
      ['1 km', '1,000 m'],
      ['1 m', '100 cm'],
      ['1 cm', '10 mm'],
      ['1 kg', '1,000 g'],
      ['1 tonne', '1,000 kg'],
      ['1 litre', '1,000 ml'],
      ['1 hour', '60 minutes'],
      ['1 minute', '60 seconds'],
      ['1 day', '24 hours'],
      ['1 week', '7 days'],
      ['1 year', '12 months'],
      ['1 decade', '10 years'],
      ['1 century', '100 years'],
      ['₦1', '100 kobo'],
      ['1 dozen', '12 items'],
    ],
  },
  {
    id: 'up-plant-parts',
    title: 'Parts of a plant and their jobs',
    subject: 'Basic Science',
    levels: ['PRIMARY'],
    leftLabel: 'Part',
    rightLabel: 'Job',
    years: ALL,
    pairs: [
      ['Root', 'Takes in water and holds the plant in the soil'],
      ['Stem', 'Holds the plant up and carries water'],
      ['Leaf', 'Makes food for the plant'],
      ['Flower', 'Produces seeds for new plants'],
      ['Fruit', 'Protects the seeds inside it'],
      ['Seed', 'Grows into a new plant'],
      ['Petal', 'Brightly coloured to attract insects'],
      ['Anther', 'Makes pollen'],
      ['Stigma', 'Receives pollen'],
      ['Ovary', 'Grows into the fruit'],
    ],
  },
  {
    id: 'up-simple-machines',
    title: 'Simple machines in everyday life',
    subject: 'Basic Science',
    levels: ['PRIMARY'],
    leftLabel: 'Example',
    rightLabel: 'Simple machine',
    years: HIGH,
    pairs: [
      ['See-saw', 'First-class lever'],
      ['Wheelbarrow', 'Second-class lever'],
      ['Tweezers', 'Third-class lever'],
      ['Wheel at the top of a flagpole', 'Pulley'],
      ['Axe blade', 'Wedge'],
      ['Ramp for loading a lorry', 'Inclined plane'],
      ['Door knob', 'Wheel and axle'],
      ['Jar lid', 'Screw'],
    ],
  },
  {
    id: 'up-festivals',
    title: 'Nigerian festivals and where they are held',
    subject: 'Social Studies',
    levels: ['PRIMARY'],
    leftLabel: 'Festival',
    rightLabel: 'Place',
    years: ALL,
    pairs: [
      ['Argungu Fishing Festival', 'Kebbi State'],
      ['Osun-Osogbo Festival', 'Osun State'],
      ['Eyo Festival', 'Lagos'],
      ['Durbar', 'Kano'],
      ['Calabar Carnival', 'Calabar'],
      ['Leboku (New Yam) Festival', 'Ugep'],
      ['Ofala Festival', 'Onitsha'],
      ['Ojude Oba Festival', 'Ijebu-Ode'],
      ['Igue Festival', 'Benin City'],
    ],
  },
  {
    id: 'up-arms-of-government',
    title: 'Government: who does what',
    subject: 'Civic Education',
    levels: ['PRIMARY'],
    leftLabel: 'Arm or office',
    rightLabel: 'Role',
    years: HIGH,
    pairs: [
      ['Legislature', 'Makes laws'],
      ['Executive', 'Carries out laws'],
      ['Judiciary', 'Interprets laws'],
      ['President', 'Head of the federal executive'],
      ['Governor', 'Head of a state government'],
      ['Chief Justice of Nigeria', 'Head of the judiciary'],
      ['Senate President', 'Leads the Senate'],
      ['Speaker', 'Leads the House of Representatives'],
      ['National Assembly', 'The Senate and the House together'],
      ['Local government chairman', 'Head of a local government council'],
      ['Supreme Court', 'The highest court in Nigeria'],
      ['INEC', 'Conducts elections'],
    ],
  },
  {
    id: 'up-deficiency-diseases',
    title: 'Deficiency diseases and their causes',
    subject: 'Basic Science',
    levels: ['PRIMARY'],
    leftLabel: 'Disease',
    rightLabel: 'Caused by lack of',
    years: HIGH,
    pairs: [
      ['Kwashiorkor', 'Protein'],
      ['Scurvy', 'Vitamin C'],
      ['Rickets', 'Vitamin D'],
      ['Goitre', 'Iodine'],
      ['Night blindness', 'Vitamin A'],
      ['Anaemia', 'Iron'],
      ['Beriberi', 'Vitamin B1'],
      ['Marasmus', 'Enough food of all kinds'],
    ],
  },
  {
    id: 'up-computer-devices',
    title: 'Computer devices and their uses',
    subject: 'Computer Studies',
    levels: ['PRIMARY'],
    leftLabel: 'Device',
    rightLabel: 'Use',
    years: ALL,
    pairs: [
      ['Keyboard', 'Typing letters and numbers'],
      ['Mouse', 'Pointing and clicking'],
      ['Monitor', 'Showing pictures and text'],
      ['Printer', 'Putting work on paper'],
      ['Speaker', 'Giving out sound'],
      ['Scanner', 'Copying a paper page into the computer'],
      ['Microphone', 'Taking in sound'],
      ['Flash drive', 'Storing and carrying files'],
      ['UPS', 'Keeping power on for a short time'],
      ['CPU', 'Processing data'],
    ],
  },
];

// ------------------------------------------------------------ true or false facts

export const UPPER_PRIMARY_FACTS: TrueFalseFact[] = [
  ...tf('m', 'Mathematics', [
    ['One million has six zeros.', true, 'One million is written 1,000,000.', 'Whole numbers', LOW],
    ['2 is the only even prime number.', true, 'Every other even number can be divided by 2, so it is not prime.', 'Prime numbers', HIGH],
    ['1 is a prime number.', false, 'A prime number has exactly two factors; 1 has only one.', 'Prime numbers', HIGH],
    ['The LCM of 4 and 10 is 40.', false, 'The LCM of 4 and 10 is 20, the smallest number both divide into.', 'LCM', HIGH],
    ['The HCF of 12 and 18 is 6.', true, '6 is the biggest number that divides both 12 and 18.', 'HCF', HIGH],
    ['0.5 is the same as 50%.', true, '0.5 = 50/100 = 50%.', 'Percentages', HIGH],
    ['3/5 is greater than 2/3.', false, '3/5 = 9/15 and 2/3 = 10/15, so 2/3 is greater.', 'Fractions', ALL],
    ['1 kilometre = 1,000 metres.', true, 'Kilo means a thousand.', 'Length', ALL],
    ['1 kilogram = 100 grams.', false, '1 kilogram = 1,000 grams.', 'Mass', ALL],
    ['1 litre = 1,000 millilitres.', true, 'There are 1,000 ml in a litre.', 'Capacity', ALL],
    ['18:00 on the 24-hour clock is 6 p.m.', true, '18 − 12 = 6, so 18:00 is 6 p.m.', 'Time', ALL],
    ['00:00 on the 24-hour clock is midnight.', true, 'A new day starts at 00:00, which is midnight.', 'Time', ALL],
    ['An acute angle is bigger than 90°.', false, 'An acute angle is less than 90°; bigger ones are obtuse or reflex.', 'Angles', ALL],
    ['The angles in a triangle add up to 360°.', false, 'They add up to 180°.', 'Angles', HIGH],
    ['All four sides of a rectangle are equal.', false, 'Only the opposite sides of a rectangle are equal.', 'Plane shapes', LOW],
    ['A cube has 6 faces.', true, 'A cube has 6 square faces, 12 edges and 8 corners.', 'Solid shapes', ALL],
    ['Area of a rectangle = length × width.', true, 'Multiply the length by the width to get the area.', 'Area', ALL],
    ['The average of 2, 4 and 9 is 5.', true, '2 + 4 + 9 = 15 and 15 ÷ 3 = 5.', 'Averages', HIGH],
    ['Simple interest = (Principal × Rate × Time) ÷ 100.', true, 'This is the simple interest formula, I = PRT ÷ 100.', 'Simple interest', P6],
    ['If the cost price is more than the selling price, there is a profit.', false, 'Selling for less than you paid is a loss.', 'Profit and loss', HIGH],
    ['25% of 200 is 50.', true, '25% is one quarter, and a quarter of 200 is 50.', 'Percentages', HIGH],
    ['XL in Roman numerals is 60.', false, 'XL is 50 − 10 = 40; LX is 60.', 'Roman numerals', LOW],
    ['Every multiple of 10 is also a multiple of 5.', true, '10 = 2 × 5, so anything times 10 is also a multiple of 5.', 'Multiples', ALL],
    ['0.25 is equal to one quarter.', true, '0.25 = 25/100 = 1/4.', 'Decimals', ALL],
    ['A number is divisible by 3 if the sum of its digits is divisible by 3.', true, 'For example 126: 1 + 2 + 6 = 9, and 126 ÷ 3 = 42.', 'Divisibility', HIGH],
    ['12 × 12 = 144.', true, '12 × 12 = 144, the square of 12.', 'Multiplication', LOW],
    ['An ordinary year has 52 weeks and 1 day.', true, '52 × 7 = 364, and 365 − 364 = 1.', 'Time', ALL],
    ['September has 31 days.', false, 'September has 30 days.', 'Time', LOW],
    ['A square has 4 lines of symmetry.', true, 'Two lines join opposite corners and two join the middles of opposite sides.', 'Symmetry', ALL],
    ['A cuboid has 8 edges.', false, 'A cuboid has 12 edges, 6 faces and 8 corners.', 'Solid shapes', ALL],
  ]),
  ...tf('e', 'English Language', [
    ['“Quickly” is an adverb.', true, 'Adverbs tell us how something is done, like quickly.', 'Parts of speech', ALL],
    ['“Beautiful” is a verb.', false, '“Beautiful” is an adjective: it describes a noun.', 'Parts of speech', ALL],
    ['The plural of “leaf” is “leafs”.', false, 'The plural of leaf is leaves.', 'Plurals', ALL],
    ['The past tense of “go” is “went”.', true, 'Go – went – gone.', 'Tenses', ALL],
    ['“Their” and “there” are homophones.', true, 'They sound the same but have different spellings and meanings.', 'Homophones', ALL],
    ['The opposite of “arrive” is “depart”.', true, 'To depart is to leave.', 'Antonyms', ALL],
    ['“Kano” is a common noun.', false, 'Kano is the name of a particular place, so it is a proper noun.', 'Nouns', ALL],
    ['“Joyful” is a synonym of “happy”.', true, 'Both words mean feeling glad.', 'Synonyms', ALL],
    ['“He don’t like rice” is correct English.', false, 'We say “He doesn’t like rice”.', 'Concord', ALL],
    ['A question ends with a full stop.', false, 'A question ends with a question mark (?).', 'Punctuation', LOW],
    ['“And”, “but” and “or” are conjunctions.', true, 'Conjunctions join words or parts of a sentence.', 'Parts of speech', ALL],
    ['“Swarm” is a collective noun used for bees.', true, 'We say a swarm of bees.', 'Nouns', ALL],
    ['The comparative of “bad” is “badder”.', false, 'Bad – worse – worst.', 'Degrees of comparison', ALL],
    ['An adjective describes a noun.', true, 'In “a red car”, red describes the car.', 'Parts of speech', ALL],
    ['“Under”, “on” and “beside” are prepositions.', true, 'Prepositions show position, like under the table.', 'Parts of speech', ALL],
    ['“Once in a blue moon” means “very often”.', false, 'It means very rarely.', 'Idioms', HIGH],
    ['“Each of the boys have a pen” is correct.', false, '“Each” is singular, so we say “Each of the boys has a pen”.', 'Concord', HIGH],
    ['The past tense of “catch” is “caught”.', true, 'Catch – caught – caught.', 'Tenses', ALL],
  ]),
  ...tf('v', 'Verbal Reasoning', [
    ['“Kitten is to cat as cub is to lion” is a correct analogy.', true, 'A kitten is a young cat and a cub is a young lion.', 'Analogies', ALL],
    ['If A = 1, B = 2 and C = 3, then CAB is coded 3-1-2.', true, 'C = 3, A = 1, B = 2.', 'Codes', ALL],
    ['“Listen” and “silent” are made from the same letters.', true, 'Both use the letters l, i, s, t, e and n.', 'Word puzzles', ALL],
    ['In the list mango, orange, carrot, pawpaw, the odd one out is orange.', false, 'Carrot is the odd one out: it is a vegetable, the others are fruits.', 'Odd one out', ALL],
  ]),
  ...tf('s', 'Basic Science', [
    ['The lungs are the main organs for breathing.', true, 'Air goes in and out of the lungs when we breathe.', 'Human body', ALL],
    ['The skeleton protects organs such as the brain and heart.', true, 'The skull protects the brain and the ribs protect the heart and lungs.', 'Human body', ALL],
    ['Veins carry blood away from the heart.', false, 'Arteries carry blood away from the heart; veins bring it back.', 'Human body', HIGH],
    ['Humans breathe out carbon dioxide.', true, 'We breathe in oxygen and breathe out carbon dioxide.', 'Human body', ALL],
    ['Green plants give out oxygen when they make food.', true, 'Photosynthesis gives out oxygen.', 'Plants', ALL],
    ['The stigma of a flower receives pollen.', true, 'Pollen lands on the sticky stigma.', 'Plants', HIGH],
    ['A whale is a fish.', false, 'A whale is a mammal: it breathes air and feeds its young with milk.', 'Animals', ALL],
    ['Frogs are amphibians.', true, 'Amphibians live both in water and on land.', 'Animals', ALL],
    ['A butterfly begins its life as an egg.', true, 'Egg, caterpillar, pupa, then adult butterfly.', 'Animals', ALL],
    ['Air has weight and takes up space.', true, 'Air is matter, so it has weight and takes up space.', 'Matter', ALL],
    ['Copper is a good conductor of electricity.', true, 'That is why electric wires are made of copper.', 'Energy', ALL],
    ['Rubber is a good conductor of electricity.', false, 'Rubber is an insulator, so it is used to cover wires.', 'Energy', ALL],
    ['A pulley is a simple machine.', true, 'A pulley helps us lift loads, like a flag up a pole.', 'Simple machines', ALL],
    ['Coal and petrol are renewable sources of energy.', false, 'They will run out one day; sunlight and wind are renewable.', 'Energy', HIGH],
    ['Sound can travel through empty space (a vacuum).', false, 'Sound needs something to travel through, such as air or water.', 'Energy', HIGH],
    ['Lack of iodine in the diet can cause goitre.', true, 'Iodised salt helps to prevent goitre.', 'Nutrition', HIGH],
    ['Oranges are a good source of vitamin C.', true, 'Citrus fruits like oranges are rich in vitamin C.', 'Nutrition', ALL],
    ['Bush burning causes air pollution.', true, 'The smoke from bush burning dirties the air.', 'Environment', ALL],
    ['Deforestation means planting many trees.', false, 'Deforestation is cutting down forests; planting trees is afforestation.', 'Environment', HIGH],
    ['The Earth goes round the sun once in about 365¼ days.', true, 'That is one year.', 'The solar system', HIGH],
    ['Mercury is the planet closest to the sun.', true, 'The order begins Mercury, Venus, Earth, Mars.', 'The solar system', HIGH],
    ['A thermometer is used to measure temperature.', true, 'Thermometers show how hot or cold something is.', 'Measurement', ALL],
    ['The kidneys help to remove waste from the blood.', true, 'The kidneys make urine from waste and extra water.', 'Human body', HIGH],
    ['Mosquitoes breed in stagnant water.', true, 'Clearing still water around the house helps to reduce mosquitoes.', 'Health', ALL],
    ['Light travels in straight lines.', true, 'That is why shadows form behind objects.', 'Energy', ALL],
    ['The front teeth used for cutting food are called incisors.', true, 'Incisors cut, canines tear and molars grind.', 'Human body', ALL],
    ['A full set of adult teeth has 32 teeth.', true, 'Adults can have 32 teeth; children have 20 milk teeth.', 'Human body', ALL],
    ['Germs that cause disease are easy to see with our eyes.', false, 'Most germs are so small that we need a microscope to see them.', 'Health', ALL],
    ['Ice melting into water is a change of state.', true, 'A solid changing into a liquid is a change of state.', 'Matter', ALL],
  ]),
  ...tf('c', 'Computer Studies', [
    ['The monitor is an output device.', true, 'It shows us the results of the computer’s work.', 'Computer parts', ALL],
    ['The mouse is an output device.', false, 'The mouse is an input device.', 'Computer parts', ALL],
    ['CPU stands for Central Processing Unit.', true, 'The CPU is the “brain” of the computer.', 'Computer parts', ALL],
    ['Software is the part of a computer you can touch.', false, 'Hardware can be touched; software is the programs.', 'Hardware and software', ALL],
    ['A flash drive can be used to store files.', true, 'A flash drive is a small storage device.', 'Storage', ALL],
    ['It is safe to share your password with strangers online.', false, 'Keep your password secret and never share it with strangers.', 'Internet safety', ALL],
    ['Switching off a computer properly is called shutting down.', true, 'Shutting down saves your work and protects the computer.', 'Using the computer', ALL],
    ['RAM stands for Random Access Memory.', true, 'RAM holds the work the computer is doing right now.', 'Storage', HIGH],
  ]),
  ...tf('ss', 'Social Studies', [
    ['Nigeria shares a border with Ghana.', false, 'Benin Republic and Togo lie between Nigeria and Ghana.', 'Nigeria and her neighbours', ALL],
    ['Nigeria shares borders with Benin, Niger, Chad and Cameroon.', true, 'These are Nigeria’s four neighbours on land.', 'Nigeria and her neighbours', ALL],
    ['The Northern and Southern Protectorates were joined in 1914.', true, 'Lord Lugard amalgamated them in 1914.', 'Nigeria’s history', ALL],
    ['Talking drums are a modern means of communication.', false, 'Talking drums are a traditional means of communication.', 'Communication', ALL],
    ['Lake Chad is in the north-east of Nigeria.', true, 'Lake Chad lies where Nigeria, Niger, Chad and Cameroon meet.', 'Geography of Nigeria', ALL],
    ['The Sahel savanna gets more rain than the rain forest.', false, 'The rain forest in the south gets the most rain.', 'Geography of Nigeria', HIGH],
    ['The Niger Delta is in the south of Nigeria.', true, 'The River Niger splits into many streams before it reaches the sea.', 'Geography of Nigeria', ALL],
    ['The Durbar festival features colourful horse riders.', true, 'Durbars are held in northern cities such as Kano, Katsina and Zaria.', 'Culture', ALL],
    ['The Osun-Osogbo festival is held in Osun State.', true, 'It is held at the Osun Sacred Grove in Osogbo.', 'Culture', ALL],
    ['The New Yam festival marks the yam harvest.', true, 'People give thanks for the new harvest of yams.', 'Culture', ALL],
    ['The rainy season is longer in the south of Nigeria than in the north.', true, 'The south is nearer the sea and gets rain for more months.', 'Climate', HIGH],
    ['The harmattan is a dry, dusty wind that blows from the Sahara.', true, 'It blows from the north-east during the dry season.', 'Climate', ALL],
    ['A nuclear family is made up of parents and their children.', true, 'An extended family also includes grandparents, uncles, aunts and cousins.', 'The family', LOW],
    ['Olumo Rock is in Abeokuta.', true, 'Olumo Rock in Abeokuta, Ogun State, is a famous tourist site.', 'Tourism', ALL],
  ]),
  ...tf('ce', 'Civic Education', [
    ['The legislature makes laws.', true, 'In Nigeria the National Assembly makes federal laws.', 'Arms of government', HIGH],
    ['The judiciary carries out the laws.', false, 'The executive carries out laws; the judiciary interprets them.', 'Arms of government', HIGH],
    ['Nigeria has 774 local government areas.', true, 'There are 774 local government areas in the 36 states and the FCT.', 'Local government', HIGH],
    ['The voting age in Nigeria is 18.', true, 'Citizens aged 18 and above can register to vote.', 'Elections', HIGH],
    ['Nigeria became a republic on 1 October 1963.', true, 'Nigeria became a republic three years after independence.', 'Nigeria’s history', HIGH],
    ['Taiwo Akinkunmi designed the Nigerian flag.', true, 'He designed the green-white-green flag while he was a student in London.', 'National symbols', ALL],
    ['The eagle on the coat of arms stands for strength.', true, 'The red eagle stands for strength.', 'National symbols', ALL],
    ['The black shield on the coat of arms stands for Nigeria’s fertile soil.', true, 'The wavy Y on it stands for the rivers Niger and Benue.', 'National symbols', ALL],
    ['Every child has the right to education.', true, 'Education is one of the rights of every child.', 'Rights and duties', ALL],
    ['Obeying traffic rules is a duty of every citizen.', true, 'Good citizens obey the laws, including traffic rules.', 'Rights and duties', ALL],
    ['Abuja is in the Federal Capital Territory.', true, 'Abuja, the capital of Nigeria, is in the FCT.', 'National symbols', ALL],
    ['The House of Representatives has 360 members.', true, 'The House of Representatives has 360 members; the Senate has 109.', 'Arms of government', P6],
    ['In 2024, Nigeria brought back the anthem “Nigeria, We Hail Thee”.', true, 'It was first used at independence in 1960 and was restored in 2024.', 'National symbols', HIGH],
  ]),
  ...tf('h', 'History', [
    ['The Oba is the traditional ruler of Benin.', true, 'The Oba of Benin rules from Benin City.', 'Pre-colonial Nigeria', ALL],
    ['Usman dan Fodio led a jihad that began in 1804.', true, 'His jihad led to the Sokoto Caliphate.', 'Pre-colonial Nigeria', HIGH],
    ['Queen Amina was a warrior queen of Zazzau.', true, 'Zazzau is the old name of the Zaria kingdom.', 'Pre-colonial Nigeria', ALL],
    ['Nok culture is known for its terracotta sculptures.', true, 'Nok heads are made of baked clay (terracotta).', 'Pre-colonial Nigeria', HIGH],
    ['The Old Oyo Empire was ruled by the Alaafin.', true, 'The Alaafin of Oyo was the ruler of the empire.', 'Pre-colonial Nigeria', ALL],
    ['The Benin bronzes were made by Hausa craftsmen.', false, 'They were made by craftsmen of the Benin Kingdom.', 'Pre-colonial Nigeria', ALL],
    ['Jaja of Opobo was a palm oil trader and king.', true, 'He founded Opobo in the Niger Delta and traded in palm oil.', 'Pre-colonial Nigeria', HIGH],
  ]),
  ...tf('ag', 'Agricultural Science', [
    ['Loamy soil is the best soil for most crops.', true, 'Loamy soil holds water well and drains well.', 'Soil', ALL],
    ['Sandy soil holds water better than clay soil.', false, 'Clay soil holds the most water; sandy soil drains fast.', 'Soil', ALL],
    ['Cocoa is a cash crop.', true, 'Cocoa is grown mainly to sell.', 'Crops', ALL],
    ['A hoe is used for making ridges and weeding.', true, 'Farmers use hoes to make ridges and remove weeds.', 'Farm tools', ALL],
    ['Goats and sheep are ruminants.', true, 'Ruminants chew the cud.', 'Farm animals', HIGH],
    ['Herbicides are used to kill insects.', false, 'Herbicides kill weeds; insecticides kill insects.', 'Crop protection', HIGH],
    ['Animal dung can be used as manure.', true, 'Dung adds nutrients to the soil.', 'Soil', ALL],
    ['Crop rotation helps to keep the soil fertile.', true, 'Growing different crops in turn stops the soil from being worn out.', 'Farming methods', HIGH],
  ]),
  ...tf('he', 'Home Economics', [
    ['Moin-moin is made from beans.', true, 'Moin-moin is steamed bean pudding.', 'Food', ALL],
    ['Wool comes from sheep.', true, 'Wool is an animal fibre from sheep.', 'Clothing', ALL],
    ['Fruits should be washed before we eat them.', true, 'Washing removes dirt and germs.', 'Food hygiene', ALL],
    ['A thimble protects the finger when sewing.', true, 'It stops the needle pricking your finger.', 'Sewing', ALL],
    ['Leftover food should be left uncovered.', false, 'Cover food to keep away flies and dirt.', 'Food hygiene', ALL],
    ['Cotton comes from an animal.', false, 'Cotton comes from the cotton plant.', 'Clothing', ALL],
  ]),
  ...tf('pe', 'Physical and Health Education', [
    ['A football match has two halves of 45 minutes each.', true, '2 × 45 = 90 minutes of play.', 'Games', ALL],
    ['A relay race is run by a team.', true, 'Team members take turns and pass a baton.', 'Athletics', ALL],
    ['Warming up before exercise helps to prevent injury.', true, 'Warming up gets the muscles ready.', 'Fitness', ALL],
    ['Smoking is good for the lungs.', false, 'Smoking damages the lungs and causes disease.', 'Health', ALL],
  ]),
];

// ------------------------------------------------------------ quiz questions

export const UPPER_PRIMARY_QUESTIONS: CuratedQuestion[] = [
  ...mcq('m', 'Mathematics', [
    ['What is the place value of 7 in 2,743,615?', '700,000', ['70,000', '7,000,000', '7,000'], 'Place value', ALL, '7 is in the hundred thousands place.'],
    ['Write two million, fifty thousand and six in figures.', '2,050,006', ['2,500,006', '2,050,060', '2,005,006'], 'Whole numbers', ALL],
    ['Round 4,682,315 to the nearest million.', '5,000,000', ['4,000,000', '4,700,000', '4,680,000'], 'Approximation', HIGH, 'The hundred thousands digit is 6, so round up.'],
    ['Round 38,476 to the nearest thousand.', '38,000', ['39,000', '38,500', '40,000'], 'Approximation', ALL, 'The hundreds digit is 4, so round down.'],
    ['What is the value of the digit 6 in 1,264,903?', '60,000', ['6,000', '600,000', '6'], 'Place value', ALL],
    ['Which is the largest number?', '1,010,100', ['1,001,100', '1,000,110', '1,010,010'], 'Whole numbers', ALL],
    ['Which of these is a prime number?', '29', ['27', '33', '39'], 'Prime numbers', HIGH, '29 has only two factors: 1 and 29.'],
    ['What are all the factors of 12?', '1, 2, 3, 4, 6, 12', ['2, 3, 4, 6', '1, 2, 4, 6, 12', '1, 2, 3, 4, 12'], 'Factors', ALL],
    ['Find the LCM of 6 and 8.', '24', ['48', '12', '2'], 'LCM', HIGH, '24 is the smallest number that both 6 and 8 divide into.'],
    ['Find the HCF of 24 and 36.', '12', ['6', '4', '72'], 'HCF', HIGH, '12 is the biggest number that divides both.'],
    ['Find the LCM of 3, 4 and 6.', '12', ['24', '72', '6'], 'LCM', HIGH],
    ['Find the HCF of 15 and 25.', '5', ['3', '75', '10'], 'HCF', HIGH],
    ['What is the next multiple of 7 after 49?', '56', ['54', '63', '50'], 'Multiples', LOW],
    ['Which number is a multiple of both 4 and 6?', '36', ['30', '26', '16'], 'Multiples', ALL, '36 = 4 × 9 and 36 = 6 × 6.'],
    ['Write 36 as a product of prime factors.', '2 × 2 × 3 × 3', ['2 × 3 × 6', '4 × 9', '2 × 2 × 9'], 'Prime factors', P6, 'Only prime numbers may appear: 2, 2, 3 and 3.'],
    ['What is the square of 12?', '144', ['24', '124', '122'], 'Squares', HIGH, '12 × 12 = 144.'],
    ['What is the square root of 81?', '9', ['8', '40.5', '18'], 'Square roots', P6, '9 × 9 = 81.'],
    ['What is 3/4 + 1/8?', '7/8', ['4/12', '4/8', '1/2'], 'Fractions', ALL, '3/4 = 6/8, and 6/8 + 1/8 = 7/8.'],
    ['What is 2/3 of 45?', '30', ['15', '27', '35'], 'Fractions', ALL, '45 ÷ 3 = 15, and 15 × 2 = 30.'],
    ['Simplify 18/24.', '3/4', ['2/3', '9/16', '6/9'], 'Fractions', ALL, 'Divide top and bottom by 6.'],
    ['Change 2¼ to an improper fraction.', '9/4', ['7/4', '11/4', '5/4'], 'Fractions', LOW, '2 × 4 + 1 = 9, so 9/4.'],
    ['Which fraction is the biggest?', '3/4', ['2/3', '5/8', '7/12'], 'Fractions', HIGH, 'With twenty-fourths: 18, 16, 15 and 14, so 3/4 is biggest.'],
    ['What is 5/6 − 1/3?', '1/2', ['4/3', '1/3', '2/3'], 'Fractions', HIGH, '1/3 = 2/6, and 5/6 − 2/6 = 3/6 = 1/2.'],
    ['What is 1/2 × 3/5?', '3/10', ['4/7', '3/7', '1/5'], 'Fractions', HIGH, 'Multiply the tops and the bottoms: 3/10.'],
    ['What is 3/4 ÷ 1/2?', '1½', ['3/8', '2/3', '1¼'], 'Fractions', P6, '3/4 × 2/1 = 6/4 = 1½.'],
    ['Write 0.75 as a fraction in its lowest terms.', '3/4', ['75/10', '7/5', '1/75'], 'Decimals', ALL, '0.75 = 75/100 = 3/4.'],
    ['Write 3/8 as a decimal.', '0.375', ['0.38', '3.8', '0.83'], 'Decimals', HIGH, '3 ÷ 8 = 0.375.'],
    ['What is 4.5 + 2.75?', '7.25', ['6.25', '7.75', '6.80'], 'Decimals', ALL],
    ['What is 10 − 3.6?', '6.4', ['7.4', '6.6', '7.6'], 'Decimals', ALL],
    ['What is 0.4 × 0.3?', '0.12', ['1.2', '0.012', '0.7'], 'Decimals', HIGH, '4 × 3 = 12, with two decimal places: 0.12.'],
    ['What is 2.4 ÷ 0.6?', '4', ['0.4', '40', '1.8'], 'Decimals', P6, '24 ÷ 6 = 4.'],
    ['Which is the smallest: 0.5, 0.05, 0.55 or 0.505?', '0.05', ['0.5', '0.55', '0.505'], 'Decimals', ALL],
    ['Write 1/5 as a decimal.', '0.2', ['0.5', '1.5', '0.15'], 'Decimals', ALL, '1/5 = 2/10 = 0.2.'],
    ['Round 3.47 to one decimal place.', '3.5', ['3.4', '3.0', '4'], 'Decimals', HIGH],
    ['What is 25% of ₦800?', '₦200', ['₦250', '₦400', '₦32'], 'Percentages', HIGH, '25% is a quarter, and ₦800 ÷ 4 = ₦200.'],
    ['Write 0.35 as a percentage.', '35%', ['3.5%', '0.35%', '350%'], 'Percentages', HIGH, 'Multiply by 100: 35%.'],
    ['Write 7/20 as a percentage.', '35%', ['70%', '27%', '14%'], 'Percentages', HIGH, '7/20 = 35/100 = 35%.'],
    ['A class has 40 pupils and 60% are girls. How many girls are there?', '24', ['16', '20', '26'], 'Percentages', HIGH, '60/100 × 40 = 24.'],
    ['Musa scored 45 out of 50 in a test. What percentage is that?', '90%', ['45%', '85%', '95%'], 'Percentages', HIGH, '45/50 = 90/100.'],
    ['Share ₦600 between Ade and Bola in the ratio 2 : 1. How much does Ade get?', '₦400', ['₦200', '₦300', '₦450'], 'Ratio', P6, '3 parts: each part is ₦200, so Ade gets 2 × ₦200.'],
    ['Write the ratio 12 : 18 in its simplest form.', '2 : 3', ['3 : 2', '4 : 6', '6 : 9'], 'Ratio', P6, 'Divide both by 6.'],
    ['A class has 15 boys and 10 girls. What is the ratio of boys to girls in its simplest form?', '3 : 2', ['2 : 3', '15 : 25', '5 : 2'], 'Ratio', P6],
    ['Mrs Okafor bought a bag of rice for ₦45,000 and sold it for ₦52,000. What was her profit?', '₦7,000', ['₦97,000', '₦17,000', '₦6,000'], 'Profit and loss', HIGH, 'Profit = selling price − cost price.'],
    ['A trader bought a radio for ₦8,000 and sold it for ₦6,500. What was the loss?', '₦1,500', ['₦2,500', '₦14,500', '₦1,000'], 'Profit and loss', HIGH, 'Loss = cost price − selling price.'],
    ['A shirt bought for ₦2,000 is sold at a profit of 20%. What is the selling price?', '₦2,400', ['₦2,200', '₦2,020', '₦1,600'], 'Profit and loss', P6, '20% of ₦2,000 is ₦400.'],
    ['Find the simple interest on ₦10,000 at 5% per year for 2 years.', '₦1,000', ['₦500', '₦2,000', '₦10,500'], 'Simple interest', P6, '10,000 × 5 × 2 ÷ 100 = 1,000.'],
    ['Find the simple interest on ₦5,000 at 4% per year for 3 years.', '₦600', ['₦200', '₦60', '₦1,200'], 'Simple interest', P6, '5,000 × 4 × 3 ÷ 100 = 600.'],
    ['Ngozi saved ₦2,000 at 10% simple interest per year. What is the total amount after 1 year?', '₦2,200', ['₦200', '₦2,020', '₦2,100'], 'Simple interest', P6, 'Interest is ₦200; amount = ₦2,000 + ₦200.'],
    ['How many kobo are there in ₦3.50?', '350', ['35', '3,500', '305'], 'Money', LOW, '₦1 = 100 kobo, so ₦3.50 = 350 kobo.'],
    ['Pens cost ₦150 each. How many pens can Aisha buy with ₦1,200?', '8', ['6', '12', '9'], 'Money', ALL, '₦1,200 ÷ ₦150 = 8.'],
    ['Tunde bought 3 exercise books at ₦250 each and a pen at ₦100. How much did he spend?', '₦850', ['₦750', '₦1,050', '₦350'], 'Money', ALL, '3 × ₦250 + ₦100 = ₦850.'],
    ['If 5 oranges cost ₦250, how much do 8 oranges cost?', '₦400', ['₦350', '₦2,000', '₦450'], 'Money', ALL, 'One orange costs ₦50; 8 × ₦50 = ₦400.'],
    ['What is 1/3 of ₦1,500?', '₦500', ['₦300', '₦450', '₦750'], 'Fractions', ALL],
    ['Convert 3.5 km to metres.', '3,500 m', ['350 m', '35,000 m', '35 m'], 'Length', ALL, '1 km = 1,000 m.'],
    ['How many centimetres are there in 2.4 m?', '240 cm', ['24 cm', '2,400 cm', '204 cm'], 'Length', ALL, '1 m = 100 cm.'],
    ['Convert 4,500 g to kilograms.', '4.5 kg', ['45 kg', '0.45 kg', '450 kg'], 'Mass', ALL, '1,000 g = 1 kg.'],
    ['How many millilitres are there in 2.5 litres?', '2,500 ml', ['250 ml', '25 ml', '25,000 ml'], 'Capacity', ALL, '1 litre = 1,000 ml.'],
    ['A tonne is equal to…', '1,000 kg', ['100 kg', '10,000 kg', '500 kg'], 'Mass', HIGH],
    ['Write 3:45 p.m. in the 24-hour clock.', '15:45', ['03:45', '13:45', '16:45'], 'Time', ALL, 'Add 12 to the hours after noon.'],
    ['What is 20:30 in the 12-hour clock?', '8:30 p.m.', ['8:30 a.m.', '10:30 p.m.', '2:30 p.m.'], 'Time', ALL, '20 − 12 = 8, in the evening.'],
    ['A lesson starts at 10:40 a.m. and lasts 45 minutes. When does it end?', '11:25 a.m.', ['11:15 a.m.', '11:45 a.m.', '11:20 a.m.'], 'Time', ALL, '20 minutes takes us to 11:00, then 25 more.'],
    ['How many seconds are there in 5 minutes?', '300', ['500', '60', '250'], 'Time', LOW, '5 × 60 = 300.'],
    ['How many days are there in 3 weeks and 4 days?', '25', ['21', '34', '28'], 'Time', LOW, '3 × 7 + 4 = 25.'],
    ['A bus left Ibadan at 07:15 and reached Lagos at 09:45. How long was the journey?', '2 hours 30 minutes', ['2 hours 15 minutes', '3 hours 30 minutes', '2 hours 45 minutes'], 'Time', ALL],
    ['How many months are there in 2½ years?', '30', ['25', '24', '36'], 'Time', ALL, '2 × 12 + 6 = 30.'],
    ['Find the perimeter of a rectangle 12 cm long and 7 cm wide.', '38 cm', ['19 cm', '84 cm', '26 cm'], 'Perimeter', ALL, '2 × (12 + 7) = 38.'],
    ['Find the area of a square with sides of 9 m.', '81 m²', ['36 m²', '18 m²', '72 m²'], 'Area', ALL, '9 × 9 = 81.'],
    ['Find the area of a triangle with base 10 cm and height 6 cm.', '30 cm²', ['60 cm²', '16 cm²', '32 cm²'], 'Area', HIGH, 'Half of base × height: ½ × 10 × 6 = 30.'],
    ['Find the volume of a cuboid 5 cm long, 4 cm wide and 3 cm high.', '60 cm³', ['12 cm³', '47 cm³', '20 cm³'], 'Volume', HIGH, '5 × 4 × 3 = 60.'],
    ['Find the volume of a cube with edges of 4 cm.', '64 cm³', ['16 cm³', '12 cm³', '48 cm³'], 'Volume', HIGH, '4 × 4 × 4 = 64.'],
    ['A garden has an area of 48 m² and a length of 8 m. What is its width?', '6 m', ['40 m', '5 m', '384 m'], 'Area', HIGH, '48 ÷ 8 = 6.'],
    ['The perimeter of a square is 36 cm. How long is one side?', '9 cm', ['6 cm', '12 cm', '18 cm'], 'Perimeter', ALL, '36 ÷ 4 = 9.'],
    ['How many degrees are there in a right angle?', '90°', ['180°', '45°', '360°'], 'Angles', LOW],
    ['The angles in a triangle add up to…', '180°', ['90°', '360°', '270°'], 'Angles', HIGH],
    ['Two angles of a triangle are 50° and 60°. What is the third angle?', '70°', ['80°', '110°', '90°'], 'Angles', HIGH, '180° − 50° − 60° = 70°.'],
    ['An angle of 120° is called…', 'an obtuse angle', ['an acute angle', 'a right angle', 'a reflex angle'], 'Angles', ALL, 'Obtuse angles are between 90° and 180°.'],
    ['Angles on a straight line add up to…', '180°', ['90°', '360°', '100°'], 'Angles', HIGH],
    ['Angles at a point add up to…', '360°', ['180°', '90°', '270°'], 'Angles', HIGH],
    ['The angles in a quadrilateral add up to…', '360°', ['180°', '270°', '400°'], 'Angles', P6],
    ['Find the average of 6, 8, 10 and 12.', '9', ['36', '10', '8'], 'Averages', HIGH, '6 + 8 + 10 + 12 = 36, and 36 ÷ 4 = 9.'],
    ['The average age of 3 children is 10 years. What is the total of their ages?', '30 years', ['13 years', '10 years', '3 years'], 'Averages', P6, 'Total = average × number = 10 × 3.'],
    ['What is the mode of 4, 7, 7, 9, 3?', '7', ['9', '3', '6'], 'Data', P6, 'The mode is the number that appears most often.'],
    ['What is the median of 3, 8, 5, 9, 6?', '6', ['5', '8', '31'], 'Data', P6, 'In order: 3, 5, 6, 8, 9. The middle number is 6.'],
    ['How many lines of symmetry does a rectangle have?', '2', ['4', '1', '0'], 'Symmetry', ALL],
    ['How many edges does a cube have?', '12', ['6', '8', '24'], 'Solid shapes', ALL],
    ['How many faces does a cuboid have?', '6', ['8', '12', '4'], 'Solid shapes', LOW],
    ['What is the Roman numeral for 49?', 'XLIX', ['IL', 'XXXXIX', 'LIX'], 'Roman numerals', LOW, 'XL = 40 and IX = 9.'],
    ['What number does XC stand for?', '90', ['110', '80', '190'], 'Roman numerals', LOW, 'X before C means 100 − 10.'],
    ['What is 4,356 + 2,879?', '7,235', ['7,135', '6,235', '7,225'], 'Addition', LOW],
    ['What is 10,000 − 3,457?', '6,543', ['7,543', '6,643', '7,457'], 'Subtraction', LOW],
    ['What is 245 × 12?', '2,940', ['2,450', '2,840', '490'], 'Multiplication', ALL, '245 × 10 = 2,450 and 245 × 2 = 490.'],
    ['What is 1,728 ÷ 12?', '144', ['142', '124', '164'], 'Division', ALL],
    ['What is 25 × 36?', '900', ['800', '960', '750'], 'Multiplication', ALL],
    ['Which number can be divided exactly by 9?', '387', ['385', '472', '239'], 'Divisibility', HIGH, '3 + 8 + 7 = 18, which divides by 9.'],
    ['What is 2³?', '8', ['6', '9', '5'], 'Indices', P6, '2 × 2 × 2 = 8.'],
    ['A car travels 60 km in 1 hour. How far does it go in 3½ hours at the same speed?', '210 km', ['180 km', '240 km', '63.5 km'], 'Speed', P6, '60 × 3.5 = 210.'],
    ['Emeka walked 4 km in 2 hours. What was his average speed?', '2 km/h', ['8 km/h', '6 km/h', '0.5 km/h'], 'Speed', P6, 'Speed = distance ÷ time.'],
    ['What is the next number: 1,250, 1,500, 1,750, …?', '2,000', ['1,850', '2,250', '1,950'], 'Number patterns', LOW],
  ]),
  ...mcq('qr', 'Quantitative Reasoning', [
    ['What comes next? 3, 7, 11, 15, …', '19', ['18', '21', '20'], 'Number patterns', ALL, 'Add 4 each time.'],
    ['What comes next? 2, 4, 8, 16, …', '32', ['24', '20', '30'], 'Number patterns', ALL, 'Double each time.'],
    ['What comes next? 1, 4, 9, 16, 25, …', '36', ['30', '35', '49'], 'Number patterns', HIGH, 'These are square numbers: 6 × 6 = 36.'],
    ['What comes next? 81, 27, 9, 3, …', '1', ['0', '2', '6'], 'Number patterns', ALL, 'Divide by 3 each time.'],
    ['What comes next? 5, 10, 20, 35, 55, …', '80', ['75', '70', '85'], 'Number patterns', P6, 'The gaps grow by 5: 5, 10, 15, 20, then 25.'],
    ['What comes next? 100, 93, 86, 79, …', '72', ['71', '73', '69'], 'Number patterns', ALL, 'Take away 7 each time.'],
    ['What comes next? 1, 1, 2, 3, 5, 8, …', '13', ['11', '12', '16'], 'Number patterns', P6, 'Add the two numbers before: 5 + 8 = 13.'],
    ['What comes next? 2, 6, 12, 20, 30, …', '42', ['40', '36', '44'], 'Number patterns', P6, 'The gaps are 4, 6, 8, 10, then 12.'],
    ['Find the missing number: 8 × ? = 96', '12', ['11', '13', '14'], 'Missing numbers', ALL],
    ['Find the missing number: ? ÷ 7 = 13', '91', ['84', '98', '20'], 'Missing numbers', ALL, '13 × 7 = 91.'],
    ['Find the missing number: 144 − ? = 89', '55', ['65', '45', '233'], 'Missing numbers', ALL],
    ['A rule turns 2 into 7, 4 into 13 and 6 into 19. What does 10 become?', '31', ['25', '30', '34'], 'Number rules', P6, 'The rule is × 3, then + 1.'],
    ['If ◻ + ◻ = 18 and ◻ + △ = 15, what is △?', '6', ['9', '3', '15'], 'Missing numbers', HIGH, '◻ = 9, so △ = 15 − 9 = 6.'],
    ['Find the missing number: 4, 9, ?, 19, 24', '14', ['13', '15', '16'], 'Number patterns', ALL, 'Add 5 each time.'],
    ['(17 + 23) ÷ 8 = ?', '5', ['40', '6', '4'], 'Operations', ALL, 'Brackets first: 40 ÷ 8 = 5.'],
    ['What number is 15 more than 3 times 12?', '51', ['45', '36', '48'], 'Operations', ALL, '3 × 12 = 36, and 36 + 15 = 51.'],
    ['If a ★ b means a × b + a, find 4 ★ 3.', '16', ['12', '19', '15'], 'Operations', P6, '4 × 3 + 4 = 16.'],
    ['If p ∆ q means p + 2q, find 5 ∆ 3.', '11', ['13', '16', '8'], 'Operations', P6, '5 + 2 × 3 = 11.'],
    ['Half of a number is 36. What is the number?', '72', ['18', '38', '70'], 'Missing numbers', ALL],
    ['Find the missing number: 3, 6, 11, 18, ?, 38', '27', ['25', '28', '29'], 'Number patterns', P6, 'The gaps are 3, 5, 7, 9, 11.'],
    ['Find the missing number: 64, 32, 16, ?, 4', '8', ['10', '12', '6'], 'Number patterns', ALL, 'Halve each time.'],
    ['What comes next? 1, 3, 6, 10, 15, …', '21', ['20', '25', '18'], 'Number patterns', HIGH, 'Add 2, 3, 4, 5, then 6.'],
    ['What is 999 + 99 + 9?', '1,107', ['1,007', '1,117', '1,097'], 'Operations', ALL],
    ['Which number is the odd one out? 2, 3, 5, 9, 11', '9', ['2', '5', '11'], 'Odd one out', HIGH, '9 is not a prime number (9 = 3 × 3).'],
    ['If 6 pens cost ₦480, how much do 10 pens cost?', '₦800', ['₦600', '₦4,800', '₦880'], 'Operations', ALL, 'One pen costs ₦80.'],
    ['A number multiplied by itself gives 169. What is the number?', '13', ['17', '14', '12'], 'Missing numbers', P6],
    ['What fraction of an hour is 20 minutes?', '1/3', ['1/2', '1/4', '1/5'], 'Fractions', ALL, '20/60 = 1/3.'],
    ['What comes next? 7, 14, 28, 56, …', '112', ['84', '70', '102'], 'Number patterns', ALL, 'Double each time.'],
    ['If the 1st of a month is a Monday, what day is the 15th?', 'Monday', ['Sunday', 'Tuesday', 'Friday'], 'Calendar', ALL, '15 is 14 days (two weeks) after the 1st.'],
    ['Find the missing number: 7 × 8 = 50 + ?', '6', ['8', '4', '16'], 'Missing numbers', LOW, '7 × 8 = 56, and 56 − 50 = 6.'],
  ]),
  ...mcq('e', 'English Language', [
    ['In “The tall boy ran quickly”, which word is an adverb?', 'quickly', ['tall', 'boy', 'ran'], 'Parts of speech', ALL],
    ['In “Chidi wore a new shirt”, which word is an adjective?', 'new', ['Chidi', 'wore', 'shirt'], 'Parts of speech', ALL],
    ['In “She gave the book to Musa”, which word is a pronoun?', 'She', ['gave', 'book', 'Musa'], 'Parts of speech', ALL],
    ['In “The cat is under the table”, which word is a preposition?', 'under', ['cat', 'is', 'table'], 'Parts of speech', ALL],
    ['In “I was tired but I finished my work”, which word is a conjunction?', 'but', ['tired', 'finished', 'work'], 'Parts of speech', ALL],
    ['Which of these is an interjection?', 'Wow!', ['quickly', 'table', 'happy'], 'Parts of speech', HIGH],
    ['“Lagos” is a … noun.', 'proper', ['common', 'abstract', 'collective'], 'Nouns', ALL, 'Names of particular places are proper nouns.'],
    ['Which of these is a collective noun?', 'herd', ['cow', 'grass', 'field'], 'Nouns', ALL, 'A herd is a group of cattle.'],
    ['Which of these is an abstract noun?', 'kindness', ['teacher', 'chair', 'Kano'], 'Nouns', HIGH, 'Abstract nouns name things we cannot touch.'],
    ['Yesterday, Bola ___ to the market.', 'went', ['go', 'goes', 'going'], 'Tenses', ALL],
    ['The past tense of “bring” is…', 'brought', ['bringed', 'brang', 'brung'], 'Tenses', ALL],
    ['The past tense of “teach” is…', 'taught', ['teached', 'thought', 'tought'], 'Tenses', ALL],
    ['The past tense of “swim” is…', 'swam', ['swum', 'swimmed', 'swims'], 'Tenses', ALL],
    ['Look! The children ___ football now.', 'are playing', ['plays', 'played', 'play'], 'Tenses', ALL],
    ['She ___ her homework before she watched TV.', 'had done', ['has done', 'does', 'do'], 'Tenses', P6],
    ['By next week, we ___ our exams.', 'will have finished', ['have finished', 'had finished', 'finishing'], 'Tenses', P6],
    ['Each of the pupils ___ a book.', 'has', ['have', 'having', 'are having'], 'Concord', HIGH, '“Each” is singular.'],
    ['Neither Musa nor his friends ___ here.', 'are', ['is', 'was', 'has'], 'Concord', P6, 'The verb agrees with the nearer subject, “friends”.'],
    ['The news ___ good today.', 'is', ['are', 'were', 'have'], 'Concord', HIGH, '“News” is singular.'],
    ['My trousers ___ torn.', 'are', ['is', 'was', 'has'], 'Concord', HIGH, '“Trousers” is always plural.'],
    ['One of the boys ___ absent.', 'is', ['are', 'were', 'have'], 'Concord', HIGH, 'The subject is “one”, which is singular.'],
    ['The plural of “child” is…', 'children', ['childs', 'childrens', 'childes'], 'Plurals', LOW],
    ['The plural of “knife” is…', 'knives', ['knifes', 'knifs', 'knive'], 'Plurals', LOW],
    ['The plural of “mouse” (the animal) is…', 'mice', ['mouses', 'mices', 'meese'], 'Plurals', LOW],
    ['The plural of “potato” is…', 'potatoes', ['potatos', 'potatoe', 'potatis'], 'Plurals', LOW],
    ['The plural of “sheep” is…', 'sheep', ['sheeps', 'sheepes', 'shoop'], 'Plurals', LOW],
    ['The plural of “baby” is…', 'babies', ['babys', 'babyes', 'babis'], 'Plurals', LOW],
    ['The plural of “tooth” is…', 'teeth', ['tooths', 'teeths', 'toothes'], 'Plurals', LOW],
    ['Which word is nearest in meaning to “begin”?', 'start', ['finish', 'stop', 'end'], 'Synonyms', ALL],
    ['Which word is nearest in meaning to “huge”?', 'enormous', ['tiny', 'narrow', 'light'], 'Synonyms', ALL],
    ['Which word is nearest in meaning to “brave”?', 'courageous', ['afraid', 'lazy', 'weak'], 'Synonyms', ALL],
    ['Which word is opposite in meaning to “ancient”?', 'modern', ['old', 'ugly', 'famous'], 'Antonyms', ALL],
    ['Which word is opposite in meaning to “generous”?', 'stingy', ['kind', 'rich', 'giving'], 'Antonyms', ALL],
    ['Which word is opposite in meaning to “accept”?', 'refuse', ['receive', 'take', 'except'], 'Antonyms', ALL],
    ['Which word is opposite in meaning to “expensive”?', 'cheap', ['costly', 'dear', 'rich'], 'Antonyms', ALL],
    ['“It was a piece of cake” means the task was…', 'very easy', ['very sweet', 'very small', 'very hard'], 'Idioms', HIGH],
    ['To “let the cat out of the bag” means to…', 'reveal a secret', ['free an animal', 'go shopping', 'lose something'], 'Idioms', HIGH],
    ['“It is raining cats and dogs” means…', 'it is raining heavily', ['animals are falling', 'it is drizzling', 'the rain has stopped'], 'Idioms', HIGH],
    ['To be “all ears” means to be…', 'listening carefully', ['very noisy', 'unable to hear', 'very sleepy'], 'Idioms', HIGH],
    ['“Once in a blue moon” means…', 'very rarely', ['every night', 'very often', 'at midnight'], 'Idioms', HIGH],
    ['Which sentence is punctuated correctly?', 'Where are you going?', ['Where are you going.', 'Where, are you going?', 'Where are you, going?'], 'Punctuation', ALL],
    ['Which sentence uses commas correctly?', 'I bought yam, rice and beans.', ['I bought, yam rice and beans.', 'I bought yam rice, and, beans.', 'I, bought yam rice and beans.'], 'Punctuation', ALL],
    ['Which shows the apostrophe used correctly?', 'the girl’s bag', ['the girls’s bag', 'the girl,s bag', 'the girls bag’s'], 'Punctuation', HIGH],
    ['Choose the right word: “I can ___ the drums from here.”', 'hear', ['here', 'hair', 'her'], 'Homophones', ALL],
    ['Choose the right word: “___ house is that?”', 'Whose', ['Who’s', 'Whos', 'Who'], 'Homophones', HIGH],
    ['Choose the right word: “They left ___ bags in the car.”', 'their', ['there', 'they’re', 'thier'], 'Homophones', ALL],
    ['Choose the right word: “The wind ___ the papers away.”', 'blew', ['blue', 'blow', 'blewed'], 'Homophones', ALL],
    ['Which pair are homophones?', 'sea and see', ['sea and sit', 'cat and cut', 'bat and ball'], 'Homophones', ALL],
    ['“The market was crowded.” “Crowded” means…', 'full of people', ['empty', 'very quiet', 'closed'], 'Vocabulary', ALL],
    ['“The pupils were punctual.” “Punctual” means…', 'on time', ['late', 'noisy', 'absent'], 'Vocabulary', ALL],
    ['“The food was delicious.” This means the food was…', 'very tasty', ['very hot', 'spoilt', 'too little'], 'Vocabulary', ALL],
    ['Which word means “a person who writes books”?', 'author', ['tailor', 'pilot', 'farmer'], 'Vocabulary', ALL],
    ['Complete: “You are coming, ___?”', 'aren’t you', ['isn’t it', 'are you', 'don’t you'], 'Question tags', P6],
    ['Complete: “She can swim, ___?”', 'can’t she', ['isn’t it', 'can she', 'doesn’t she'], 'Question tags', P6],
    ['Ada is the ___ girl in the class.', 'tallest', ['taller', 'tall', 'most tallest'], 'Degrees of comparison', ALL],
    ['This mango is ___ than that one.', 'sweeter', ['sweetest', 'more sweeter', 'sweet'], 'Degrees of comparison', ALL],
    ['The comparative form of “good” is…', 'better', ['gooder', 'best', 'more good'], 'Degrees of comparison', ALL],
    ['Choose the correct spelling.', 'necessary', ['neccessary', 'necesary', 'neccesary'], 'Spelling', P6],
  ]),
  ...mcq('vr', 'Verbal Reasoning', [
    ['Bird is to nest as bee is to…', 'hive', ['honey', 'flower', 'sting'], 'Analogies', ALL],
    ['Doctor is to hospital as teacher is to…', 'school', ['pupil', 'chalk', 'market'], 'Analogies', ALL],
    ['Big is to small as tall is to…', 'short', ['high', 'long', 'thin'], 'Analogies', ALL],
    ['Cow is to moo as dog is to…', 'bark', ['purr', 'neigh', 'bleat'], 'Analogies', LOW],
    ['Pen is to write as knife is to…', 'cut', ['eat', 'sharp', 'kitchen'], 'Analogies', ALL],
    ['Kitten is to cat as puppy is to…', 'dog', ['kid', 'calf', 'lamb'], 'Analogies', LOW],
    ['Eye is to see as ear is to…', 'hear', ['smell', 'taste', 'touch'], 'Analogies', LOW],
    ['Seven is to week as twelve is to…', 'year', ['month', 'day', 'hour'], 'Analogies', ALL, 'A week has 7 days and a year has 12 months.'],
    ['Mother is to daughter as father is to…', 'son', ['brother', 'uncle', 'nephew'], 'Analogies', ALL],
    ['Which is the odd one out?', 'carrot', ['mango', 'orange', 'pawpaw'], 'Odd one out', LOW, 'Carrot is a vegetable; the others are fruits.'],
    ['Which is the odd one out?', 'Ghana', ['Kano', 'Lagos', 'Enugu'], 'Odd one out', ALL, 'Ghana is a country; the others are Nigerian states.'],
    ['Which is the odd one out?', 'cube', ['square', 'triangle', 'circle'], 'Odd one out', HIGH, 'A cube is a solid shape; the others are flat.'],
    ['Which is the odd one out?', 'happy', ['run', 'jump', 'swim'], 'Odd one out', ALL, 'Happy is an adjective; the others are verbs.'],
    ['Which is the odd one out?', 'bat', ['eagle', 'hawk', 'parrot'], 'Odd one out', HIGH, 'A bat is a mammal; the others are birds.'],
    ['Which is the odd one out?', 'June', ['Monday', 'Friday', 'Sunday'], 'Odd one out', LOW, 'June is a month; the others are days.'],
    ['Which is the odd one out?', 'sad', ['happy', 'glad', 'cheerful'], 'Odd one out', ALL],
    ['If CAT is written as DBU, how is DOG written?', 'EPH', ['EPG', 'FQI', 'DPH'], 'Codes', HIGH, 'Each letter moves one place forward.'],
    ['If BOOK is coded 2-15-15-11, what is the code for COOK?', '3-15-15-11', ['3-16-16-11', '2-15-15-12', '4-15-15-11'], 'Codes', HIGH, 'Each letter is its place in the alphabet; C is 3.'],
    ['If MAN is written as NAM, how is TOP written?', 'POT', ['OPT', 'TPO', 'PTO'], 'Codes', ALL, 'The word is written backwards.'],
    ['If 1 = A, 2 = B, 3 = C and so on, what word is 2-1-7?', 'BAG', ['BAD', 'CAG', 'BAH'], 'Codes', ALL],
    ['If BLUE is coded as CMVF, what is the code for RED?', 'SFE', ['QDC', 'SFD', 'RFE'], 'Codes', P6, 'Each letter moves one place forward.'],
    ['Which word can be made from the letters of TEACHER?', 'cheat', ['torch', 'beach', 'peach'], 'Word puzzles', HIGH],
    ['Which word goes with book, magazine and newspaper?', 'journal', ['pencil', 'radio', 'table'], 'Word families', ALL],
    ['Which word completes both: foot___ and ___room?', 'ball', ['step', 'class', 'wear'], 'Word puzzles', P6, 'Football and ballroom.'],
    ['Rearrange ANGHA to make a West African country.', 'Ghana', ['Gabon', 'Guinea', 'Chad'], 'Word puzzles', ALL],
    ['Which word comes first in a dictionary?', 'label', ['ladder', 'lamp', 'lane'], 'Alphabetical order', ALL, 'lab… comes before lad…, lam… and lan….'],
  ]),
  ...mcq('s', 'Basic Science', [
    ['Which organ helps us to breathe?', 'The lungs', ['The kidneys', 'The liver', 'The stomach'], 'Human body', ALL],
    ['Which organ removes waste from the blood to make urine?', 'The kidneys', ['The lungs', 'The heart', 'The brain'], 'Human body', HIGH],
    ['Where does the digestion of food begin?', 'In the mouth', ['In the stomach', 'In the large intestine', 'In the liver'], 'Human body', ALL, 'Teeth and saliva start digestion in the mouth.'],
    ['Which organ controls the whole body?', 'The brain', ['The heart', 'The liver', 'The lungs'], 'Human body', ALL],
    ['How many bones are in an adult human skeleton?', '206', ['106', '306', '201'], 'Human body', HIGH],
    ['Which blood vessels carry blood away from the heart?', 'Arteries', ['Veins', 'Capillaries', 'Nerves'], 'Human body', HIGH],
    ['Which gas does our body need from the air we breathe in?', 'Oxygen', ['Carbon dioxide', 'Nitrogen', 'Hydrogen'], 'Human body', ALL],
    ['Which gas do green plants take in to make food?', 'Carbon dioxide', ['Oxygen', 'Nitrogen', 'Helium'], 'Plants', ALL],
    ['The green colouring in leaves is called…', 'chlorophyll', ['chloride', 'pollen', 'sap'], 'Plants', HIGH],
    ['Which part of a flower makes pollen?', 'The anther', ['The stigma', 'The petal', 'The ovary'], 'Plants', HIGH],
    ['Which of these plants does not produce flowers?', 'Fern', ['Mango tree', 'Hibiscus', 'Maize'], 'Plants', HIGH],
    ['Animals that eat only plants are called…', 'herbivores', ['carnivores', 'omnivores', 'decomposers'], 'Animals', ALL],
    ['Which of these is a mammal?', 'Whale', ['Shark', 'Crocodile', 'Ostrich'], 'Animals', ALL, 'Whales breathe air and feed their young with milk.'],
    ['Which of these animals is cold-blooded?', 'Lizard', ['Goat', 'Dog', 'Hen'], 'Animals', HIGH],
    ['Animals without a backbone are called…', 'invertebrates', ['vertebrates', 'mammals', 'reptiles'], 'Animals', HIGH],
    ['Which of these is an insect?', 'Housefly', ['Spider', 'Scorpion', 'Millipede'], 'Animals', ALL, 'Insects have six legs.'],
    ['The three states of matter are solid, liquid and…', 'gas', ['ice', 'water', 'heat'], 'Matter', ALL],
    ['Which of these is a liquid at room temperature?', 'Kerosene', ['Stone', 'Sugar', 'Air'], 'Matter', ALL],
    ['A liquid changing into vapour when heated is called…', 'evaporation', ['condensation', 'freezing', 'melting'], 'Matter', ALL],
    ['Which of these is a good conductor of electricity?', 'Copper', ['Plastic', 'Rubber', 'Wood'], 'Energy', ALL],
    ['The energy stored in food is … energy.', 'chemical', ['sound', 'light', 'electrical'], 'Energy', HIGH],
    ['A dry cell (battery) changes chemical energy into…', 'electrical energy', ['sound energy', 'nuclear energy', 'wind energy'], 'Energy', HIGH],
    ['Which of these is a renewable source of energy?', 'Sunlight', ['Coal', 'Petrol', 'Kerosene'], 'Energy', HIGH],
    ['A see-saw is an example of a…', 'lever', ['pulley', 'wheel and axle', 'screw'], 'Simple machines', ALL],
    ['Which simple machine helps to raise a flag up a pole?', 'Pulley', ['Lever', 'Wedge', 'Screw'], 'Simple machines', ALL],
    ['A ramp used to push a drum onto a lorry is called…', 'an inclined plane', ['a pulley', 'a lever', 'a wedge'], 'Simple machines', ALL],
    ['The blade of an axe is an example of a…', 'wedge', ['pulley', 'screw', 'wheel and axle'], 'Simple machines', HIGH],
    ['Simple machines make work…', 'easier', ['harder', 'impossible', 'slower'], 'Simple machines', LOW],
    ['Which class of food builds and repairs the body?', 'Proteins', ['Carbohydrates', 'Fats and oils', 'Water'], 'Nutrition', ALL],
    ['Which of these foods is rich in protein?', 'Beans', ['Garri', 'Yam', 'Sugar'], 'Nutrition', ALL],
    ['Lack of vitamin C causes…', 'scurvy', ['rickets', 'goitre', 'malaria'], 'Nutrition', HIGH],
    ['Lack of vitamin D causes…', 'rickets', ['scurvy', 'night blindness', 'kwashiorkor'], 'Nutrition', HIGH],
    ['A diet with all the food classes in the right amounts is a…', 'balanced diet', ['heavy diet', 'fast food', 'snack'], 'Nutrition', ALL],
    ['Cholera is mainly spread through…', 'dirty water and food', ['mosquito bites', 'cold weather', 'loud noise'], 'Health', ALL],
    ['Which planet is closest to the sun?', 'Mercury', ['Venus', 'Earth', 'Mars'], 'The solar system', HIGH],
    ['What causes day and night?', 'The Earth spinning on its axis', ['The Earth moving round the sun', 'The moon covering the sun', 'Clouds blocking the sun'], 'The solar system', HIGH],
    ['Which of these causes air pollution?', 'Smoke from bush burning', ['Planting trees', 'Rainfall', 'Sunshine'], 'Environment', ALL],
    ['Soil erosion is best prevented by…', 'planting trees and grass', ['cutting down trees', 'bush burning', 'overgrazing'], 'Environment', HIGH],
    ['Which instrument measures temperature?', 'Thermometer', ['Barometer', 'Ruler', 'Rain gauge'], 'Measurement', ALL],
    ['Which instrument measures rainfall?', 'Rain gauge', ['Thermometer', 'Wind vane', 'Barometer'], 'Weather', ALL],
    ['A magnet will attract…', 'iron nails', ['wood', 'plastic spoons', 'paper'], 'Magnets', ALL],
    ['Teeth used for grinding food are called…', 'molars', ['incisors', 'canines', 'gums'], 'Human body', ALL],
  ]),
  ...mcq('c', 'Computer Studies', [
    ['Which part of a computer is called its “brain”?', 'The CPU', ['The monitor', 'The mouse', 'The keyboard'], 'Computer parts', ALL],
    ['Which of these is an input device?', 'Keyboard', ['Printer', 'Monitor', 'Speaker'], 'Computer parts', ALL],
    ['Which of these is an output device?', 'Printer', ['Mouse', 'Scanner', 'Keyboard'], 'Computer parts', ALL],
    ['Which of these is a storage device?', 'Flash drive', ['Mouse', 'Speaker', 'Monitor'], 'Storage', ALL],
    ['The parts of a computer you can touch are called…', 'hardware', ['software', 'data', 'the internet'], 'Hardware and software', ALL],
    ['The programs that run on a computer are called…', 'software', ['hardware', 'cables', 'monitors'], 'Hardware and software', ALL],
    ['Who is known as the father of the computer?', 'Charles Babbage', ['Isaac Newton', 'Thomas Edison', 'Alexander Graham Bell'], 'History of computers', HIGH],
    ['Which key puts a space between words?', 'Space bar', ['Enter key', 'Shift key', 'Delete key'], 'Using the keyboard', LOW],
    ['What does UPS stand for?', 'Uninterruptible Power Supply', ['Universal Power System', 'Unit Power Supply', 'Upper Power Source'], 'Computer parts', HIGH],
    ['A computer virus is…', 'a harmful program', ['a germ in the air', 'a type of mouse', 'a part of the monitor'], 'Computer safety', HIGH],
  ]),
  ...mcq('ss', 'Social Studies', [
    ['In which year were the Northern and Southern Protectorates joined?', '1914', ['1960', '1900', '1963'], 'Nigeria’s history', ALL],
    ['Who joined (amalgamated) the Northern and Southern Protectorates of Nigeria?', 'Lord Lugard', ['Herbert Macaulay', 'Nnamdi Azikiwe', 'Mungo Park'], 'Nigeria’s history', HIGH],
    ['Which country shares Nigeria’s western border?', 'Benin Republic', ['Cameroon', 'Chad', 'Ghana'], 'Nigeria and her neighbours', ALL],
    ['Which country is Nigeria’s neighbour to the east?', 'Cameroon', ['Niger', 'Benin Republic', 'Togo'], 'Nigeria and her neighbours', ALL],
    ['Which ocean lies to the south of Nigeria?', 'The Atlantic Ocean', ['The Indian Ocean', 'The Pacific Ocean', 'The Arctic Ocean'], 'Geography of Nigeria', ALL],
    ['Which is the fastest means of transport?', 'Air', ['Rail', 'Road', 'Water'], 'Transport', LOW],
    ['Which is the cheapest way to carry heavy goods across the sea?', 'Ships', ['Aeroplanes', 'Lorries', 'Wheelbarrows'], 'Transport', ALL],
    ['Which of these is a modern means of communication?', 'Mobile phone', ['Talking drum', 'Town crier', 'Smoke signal'], 'Communication', LOW],
    ['The town crier and the talking drum are … means of communication.', 'traditional', ['modern', 'electronic', 'digital'], 'Communication', LOW],
    ['Which cash crop is grown mainly in northern Nigeria?', 'Groundnut', ['Cocoa', 'Rubber', 'Oil palm'], 'Economic activities', HIGH],
    ['Cocoa is grown mainly in which part of Nigeria?', 'The South-West', ['The North-East', 'The North-West', 'The far north'], 'Economic activities', HIGH],
    ['Which vegetation zone is found in the far north of Nigeria?', 'Sahel savanna', ['Mangrove swamp', 'Rain forest', 'Guinea savanna'], 'Geography of Nigeria', HIGH],
    ['A family of a father, a mother and their children only is called…', 'a nuclear family', ['an extended family', 'a clan', 'a community'], 'The family', LOW],
    ['What is the highest point in Nigeria?', 'Chappal Waddi', ['Obudu Plateau', 'Zuma Rock', 'Olumo Rock'], 'Geography of Nigeria', P6],
    ['Olumo Rock is in which city?', 'Abeokuta', ['Ibadan', 'Kano', 'Enugu'], 'Tourism', ALL],
    ['The dry, dusty wind that blows from the Sahara is called…', 'the harmattan', ['the monsoon', 'a sea breeze', 'a hurricane'], 'Climate', ALL],
    ['The Rivers Niger and Benue meet at which town?', 'Lokoja', ['Onitsha', 'Makurdi', 'Jebba'], 'Geography of Nigeria', HIGH],
    ['The Eyo festival is held in…', 'Lagos', ['Kano', 'Calabar', 'Sokoto'], 'Culture', ALL],
    ['Which of these is a good way to greet elders in Nigeria?', 'Greeting them politely and respectfully', ['Ignoring them', 'Shouting at them', 'Walking past without a word'], 'Culture', LOW],
  ]),
  ...mcq('ce', 'Civic Education', [
    ['Which arm of government makes laws?', 'The legislature', ['The judiciary', 'The executive', 'The police'], 'Arms of government', HIGH],
    ['Which arm of government carries out laws?', 'The executive', ['The legislature', 'The judiciary', 'The press'], 'Arms of government', HIGH],
    ['Nigeria’s National Assembly is made up of the Senate and the…', 'House of Representatives', ['House of Lords', 'State House of Assembly', 'Federal Executive Council'], 'Arms of government', HIGH],
    ['How many members does the House of Representatives have?', '360', ['109', '36', '469'], 'Arms of government', P6],
    ['What is the highest court in Nigeria?', 'The Supreme Court', ['The High Court', 'The Magistrate Court', 'The Customary Court'], 'Arms of government', HIGH],
    ['Who heads the judiciary in Nigeria?', 'The Chief Justice of Nigeria', ['The President', 'The Senate President', 'The Speaker'], 'Arms of government', P6],
    ['Who heads the executive arm of the federal government?', 'The President', ['The Chief Justice', 'The Senate President', 'The Speaker'], 'Arms of government', HIGH],
    ['Who wrote the Nigerian National Pledge?', 'Felicia Adebola Adeyoyin', ['Taiwo Akinkunmi', 'Benedict Odiase', 'Herbert Macaulay'], 'National symbols', HIGH],
    ['Who designed the Nigerian flag?', 'Taiwo Akinkunmi', ['Benedict Odiase', 'Nnamdi Azikiwe', 'Felicia Adeyoyin'], 'National symbols', ALL],
    ['The National Pledge begins: “I pledge to Nigeria my…”', 'country', ['state', 'family', 'home'], 'National symbols', ALL],
    ['Which national anthem did Nigeria bring back in 2024?', 'Nigeria, We Hail Thee', ['Arise, O Compatriots', 'God Bless Nigeria', 'One Nigeria'], 'National symbols', HIGH],
    ['In the Nigerian flag, the white colour stands for…', 'peace and unity', ['agriculture', 'wealth', 'strength'], 'National symbols', ALL],
    ['What is the red bird on top of the Nigerian coat of arms?', 'An eagle', ['A parrot', 'An owl', 'A hawk'], 'National symbols', ALL],
    ['What supports the shield on the Nigerian coat of arms?', 'Two white horses', ['Two lions', 'Two eagles', 'Two elephants'], 'National symbols', ALL],
    ['The Y shape on the coat of arms stands for…', 'the Rivers Niger and Benue', ['the roads to Abuja', 'two mountains', 'the Atlantic coast'], 'National symbols', ALL],
    ['What is Nigeria’s motto?', 'Unity and Faith, Peace and Progress', ['One Nation, One Destiny', 'Faith, Hope and Love', 'Work and Happiness'], 'National symbols', ALL],
    ['Which of these is a right of every Nigerian child?', 'The right to education', ['The right to vote', 'The right to drive a car', 'The right to skip school'], 'Rights and duties', ALL],
    ['Which of these is a duty of a good citizen?', 'Obeying the laws', ['Destroying public property', 'Cheating in exams', 'Dropping litter'], 'Rights and duties', ALL],
    ['At what age can a Nigerian vote in elections?', '18 years', ['16 years', '21 years', '15 years'], 'Elections', HIGH],
    ['How many local government areas are there in Nigeria?', '774', ['744', '36', '109'], 'Local government', HIGH],
    ['Which body conducts elections in Nigeria?', 'INEC', ['NAFDAC', 'NEPA', 'WAEC'], 'Elections', P6],
    ['Telling the truth at all times is called…', 'honesty', ['laziness', 'pride', 'greed'], 'Values', LOW],
  ]),
  ...mcq('h', 'History', [
    ['The traditional ruler of the Benin Kingdom is called the…', 'Oba', ['Emir', 'Alaafin', 'Obi'], 'Pre-colonial Nigeria', ALL],
    ['The ruler of the Old Oyo Empire was called the…', 'Alaafin', ['Oba of Benin', 'Emir', 'Shehu'], 'Pre-colonial Nigeria', ALL],
    ['The Benin Kingdom is famous for works of art made of…', 'bronze', ['plastic', 'glass', 'paper'], 'Pre-colonial Nigeria', ALL],
    ['Who led the jihad of 1804 that founded the Sokoto Caliphate?', 'Usman dan Fodio', ['Queen Amina', 'Oduduwa', 'Jaja of Opobo'], 'Pre-colonial Nigeria', HIGH],
    ['Queen Amina was a famous warrior queen of…', 'Zazzau (Zaria)', ['Benin', 'Oyo', 'Opobo'], 'Pre-colonial Nigeria', ALL],
    ['Ile-Ife is regarded as the ancestral home of the…', 'Yoruba', ['Hausa', 'Igbo', 'Ijaw'], 'Pre-colonial Nigeria', ALL],
    ['The Kanem-Borno Empire grew up around which lake?', 'Lake Chad', ['Kainji Lake', 'Lake Victoria', 'Oguta Lake'], 'Pre-colonial Nigeria', HIGH],
    ['Jaja of Opobo was a famous…', 'trader and king in the Niger Delta', ['Hausa emir', 'Yoruba poet', 'British governor'], 'Pre-colonial Nigeria', HIGH],
    ['The Nok culture is famous for its…', 'terracotta (baked clay) sculptures', ['bronze heads', 'stone castles', 'gold coins'], 'Pre-colonial Nigeria', HIGH],
    ['Igbo-Ukwu is famous for its ancient…', 'bronze works', ['stone walls', 'wooden ships', 'clay pyramids'], 'Pre-colonial Nigeria', HIGH],
    ['How many states were the original “Hausa Bakwai”?', 'Seven', ['Five', 'Nine', 'Twelve'], 'Pre-colonial Nigeria', P6, '“Bakwai” means seven in Hausa.'],
    ['Who was Nigeria’s first Prime Minister?', 'Sir Abubakar Tafawa Balewa', ['Nnamdi Azikiwe', 'Obafemi Awolowo', 'Herbert Macaulay'], 'Nigeria’s history', HIGH],
    ['Who was Nigeria’s first President?', 'Nnamdi Azikiwe', ['Abubakar Tafawa Balewa', 'Obafemi Awolowo', 'Ahmadu Bello'], 'Nigeria’s history', HIGH],
    ['In which year did Nigeria become a republic?', '1963', ['1960', '1914', '1966'], 'Nigeria’s history', HIGH],
  ]),
  ...mcq('ag', 'Agricultural Science', [
    ['Which of these is mainly a food crop?', 'Yam', ['Cotton', 'Rubber', 'Cocoa'], 'Crops', ALL],
    ['Which of these is a cash crop?', 'Rubber', ['Okra', 'Spinach', 'Garden egg'], 'Crops', ALL],
    ['Which farm tool is used for clearing grass?', 'Cutlass', ['Watering can', 'Rake', 'Wheelbarrow'], 'Farm tools', ALL],
    ['Which farm tool is used for carrying soil and manure?', 'Wheelbarrow', ['Cutlass', 'Hoe', 'Secateurs'], 'Farm tools', ALL],
    ['Which type of soil is best for growing most crops?', 'Loamy soil', ['Sandy soil', 'Clay soil', 'Rocky soil'], 'Soil', ALL],
    ['Which type of soil holds the most water?', 'Clay soil', ['Sandy soil', 'Loamy soil', 'Gravel'], 'Soil', ALL],
    ['Which of these is poultry?', 'Chickens', ['Goats', 'Pigs', 'Rabbits'], 'Farm animals', LOW],
    ['Keeping bees for honey is called…', 'apiculture', ['poultry', 'piggery', 'fishery'], 'Farm animals', HIGH],
    ['Manure made from rotting plant and animal waste is called…', 'compost', ['herbicide', 'pesticide', 'insecticide'], 'Soil', HIGH],
    ['A chemical used to kill weeds is called a…', 'herbicide', ['insecticide', 'fungicide', 'fertiliser'], 'Crop protection', HIGH],
    ['Which of these animals chews the cud?', 'Cow', ['Pig', 'Dog', 'Hen'], 'Farm animals', HIGH],
    ['Rearing fish in ponds is called…', 'fish farming', ['bee keeping', 'poultry', 'crop rotation'], 'Farm animals', ALL],
  ]),
  ...mcq('he', 'Home Economics', [
    ['Which of these is a cleaning agent?', 'Soap', ['Sugar', 'Flour', 'Palm oil'], 'Home management', LOW],
    ['Which method of cooking uses hot oil?', 'Frying', ['Boiling', 'Steaming', 'Roasting'], 'Cooking methods', ALL],
    ['Moin-moin is usually cooked by…', 'steaming', ['frying', 'grilling', 'roasting'], 'Cooking methods', ALL],
    ['Which fabric comes from an animal?', 'Wool', ['Cotton', 'Linen', 'Nylon'], 'Clothing', HIGH],
    ['Cotton fabric comes from…', 'a plant', ['an animal', 'a rock', 'the sea'], 'Clothing', ALL],
    ['Which sewing tool protects the finger?', 'Thimble', ['Tape measure', 'Pin cushion', 'Bobbin'], 'Sewing', ALL],
    ['Good personal hygiene includes…', 'bathing every day', ['sharing toothbrushes', 'biting nails', 'wearing dirty clothes'], 'Personal hygiene', LOW],
    ['We should brush our teeth at least…', 'twice a day', ['once a week', 'once a month', 'twice a week'], 'Personal hygiene', LOW],
    ['Which kitchen utensil is used to drain water from boiled rice?', 'Colander', ['Grater', 'Ladle', 'Rolling pin'], 'Kitchen equipment', ALL],
  ]),
  ...mcq('pe', 'Physical and Health Education', [
    ['How many players does a football team have on the pitch?', '11', ['9', '7', '15'], 'Games', ALL],
    ['How many players does a basketball team have on the court?', '5', ['6', '7', '11'], 'Games', ALL],
    ['Regular exercise helps to…', 'keep the body fit', ['cause sickness', 'make bones weak', 'stop growth'], 'Fitness', LOW],
    ['The first thing to do for a small cut is to…', 'clean it and cover it', ['rub sand on it', 'leave it dirty', 'pour kerosene on it'], 'First aid', ALL],
  ]),
];

// ------------------------------------------------------------ spelling words

export const UPPER_PRIMARY_WORDS: GameWord[] = words([
  // Common spelling words
  ['receipt', 'a paper that shows you have paid', 'Keep the receipt after you pay.', ALL],
  ['grammar', 'the rules of a language', 'We learn grammar in English lessons.', ALL],
  ['calendar', 'a chart of days and months', 'Mark the date on the calendar.', ALL],
  ['surprise', 'something you did not expect', 'Mama gave us a surprise on my birthday.', ALL],
  ['thought', 'an idea in your mind', 'I had a good thought about the story.', ALL],
  ['though', 'even if; although', 'It was hot, though the fan was on.', ALL],
  ['through', 'from one side to the other', 'We walked through the market.', ALL],
  ['weight', 'how heavy something is', 'Find the weight of the bag of rice.', ALL],
  ['height', 'how tall something is', 'Measure your height with a tape.', ALL],
  ['guard', 'a person who protects a place', 'The guard opened the school gate.', ALL],
  ['guess', 'to give an answer without being sure', 'Can you guess my age?', ALL],
  ['exercise', 'a task to practise; or activity to keep fit', 'Do the exercise in your notebook.', ALL],
  ['holiday', 'time off from school or work', 'We travelled to Jos during the holiday.', ALL],
  ['address', 'where someone lives', 'Write your home address on the envelope.', ALL],
  ['envelope', 'a paper cover for a letter', 'Put the letter in an envelope.', ALL],
  ['question', 'something you ask', 'Raise your hand to ask a question.', ALL],
  ['village', 'a small community in the countryside', 'My grandmother lives in a village near Nsukka.', ALL],
  ['country', 'a nation with its own land and government', 'Nigeria is a large country.', ALL],
  ['language', 'the words people use to speak and write', 'Hausa is a language spoken by many people in Kano.', ALL],
  ['eighth', 'number eight in order', 'August is the eighth month of the year.', ALL],
  ['forty', 'the number 40', 'There are forty pupils in our class.', ALL],
  ['ninety', 'the number 90', 'Grandpa is ninety years old.', ALL],
  ['piece', 'a part of something', 'May I have a piece of cake?', ALL],
  ['peace', 'a time without fighting', 'White on our flag stands for peace.', ALL],
  ['quiet', 'making little or no noise', 'Please be quiet in the library.', ALL],
  ['quite', 'fairly; rather', 'The test was quite easy.', ALL],
  ['especially', 'more than usual; above all', 'I like fruit, especially mangoes.', HIGH],
  ['probably', 'very likely', 'It will probably rain today.', HIGH],
  ['restaurant', 'a place where you buy and eat meals', 'We ate pounded yam at a restaurant.', HIGH],
  ['sentence', 'a group of words that makes complete sense', 'Write a sentence with a verb in it.', ALL],
  ['paragraph', 'a group of sentences about one idea', 'Start a new paragraph for a new idea.', ALL],
  ['dictionary', 'a book that gives the meanings of words', 'Check the meaning in a dictionary.', ALL],
  ['opposite', 'completely different', 'The opposite of hot is cold.', ALL],
  ['vowel', 'the letters a, e, i, o and u', 'The letter e is a vowel.', LOW],
  ['adjective', 'a word that describes a noun', 'An adjective describes a noun.', ALL],
  ['pronoun', 'a word used instead of a noun', '“She” is a pronoun.', ALL],
  ['preposition', 'a word that shows position, like “under”', '“Under” is a preposition.', HIGH],
  ['conjunction', 'a joining word, like “and” or “but”', '“But” is a conjunction.', HIGH],
  ['sincerely', 'honestly; used to end a formal letter', 'End the letter with “Yours sincerely”.', P6],
  ['disappear', 'to go out of sight', 'The sun will disappear behind the clouds.', HIGH],
  ['tongue', 'the part of the mouth used for tasting', 'We taste food with our tongue.', ALL],
  ['scissors', 'a tool with two blades for cutting', 'Cut the paper with scissors.', ALL],
  ['whistle', 'a small tool that makes a high sound', 'The referee blew the whistle.', ALL],
  ['achievement', 'something done well through effort', 'Winning the quiz was a great achievement.', P6],
  // Mathematics
  ['hundred', 'the number 100', 'A hundred kobo make one naira.', LOW, 'Mathematics'],
  ['thousand', 'the number 1,000', 'One thousand metres make a kilometre.', ALL, 'Mathematics'],
  ['million', 'the number 1,000,000', 'Over a million people visited the fair.', ALL, 'Mathematics'],
  ['fraction', 'a part of a whole, such as one half', 'One quarter is a fraction.', ALL, 'Mathematics'],
  ['decimal', 'a number with a point, such as 0.5', 'Write the answer as a decimal.', ALL, 'Mathematics'],
  ['percentage', 'a part out of a hundred', 'Write the score as a percentage.', HIGH, 'Mathematics'],
  ['average', 'the total shared equally', 'Find the average of the marks.', HIGH, 'Mathematics'],
  ['multiply', 'to find the product of numbers', 'We multiply to find the total cost.', ALL, 'Mathematics'],
  ['divide', 'to share into equal groups', 'Please divide the oranges equally.', ALL, 'Mathematics'],
  ['triangle', 'a shape with three sides', 'A triangle has three angles.', ALL, 'Mathematics'],
  ['rectangle', 'a four-sided shape with four right angles', 'The football field is a rectangle.', ALL, 'Mathematics'],
  ['diameter', 'a line across a circle through its centre', 'The diameter of the plate is 20 cm.', HIGH, 'Mathematics'],
  ['volume', 'the space a solid takes up', 'Find the volume of the box.', HIGH, 'Mathematics'],
  ['interest', 'money paid for saving or borrowing money', 'The bank paid interest on her savings.', P6, 'Mathematics'],
  ['profit', 'money gained when you sell for more than you paid', 'The trader made a profit of ₦500.', HIGH, 'Mathematics'],
  ['calculate', 'to work out with numbers', 'Use the rule to calculate the area.', ALL, 'Mathematics'],
  ['measure', 'to find the size or amount of something', 'Use a ruler to measure the line.', ALL, 'Mathematics'],
  ['kilometre', 'one thousand metres', 'Our school is one kilometre from my house.', ALL, 'Mathematics'],
  ['centimetre', 'one hundredth of a metre', 'Each side is one centimetre long.', ALL, 'Mathematics'],
  ['litre', 'a unit for measuring liquids', 'Buy one litre of groundnut oil.', ALL, 'Mathematics'],
  // Basic Science
  ['skeleton', 'all the bones of the body', 'The skeleton supports the body.', ALL, 'Basic Science'],
  ['muscle', 'body tissue that helps us move', 'The heart is a muscle.', ALL, 'Basic Science'],
  ['stomach', 'the organ where food is digested', 'Food is digested in the stomach.', ALL, 'Basic Science'],
  ['kidney', 'an organ that cleans the blood', 'Each kidney cleans the blood.', HIGH, 'Basic Science'],
  ['oxygen', 'the gas we need to breathe', 'We need oxygen to live.', ALL, 'Basic Science'],
  ['nutrition', 'the food we need to grow and stay healthy', 'Good nutrition helps children grow.', HIGH, 'Basic Science'],
  ['protein', 'a food class that builds the body', 'Beans and fish give us protein.', ALL, 'Basic Science'],
  ['vitamin', 'a food substance that keeps us healthy', 'Oranges are rich in vitamin C.', ALL, 'Basic Science'],
  ['machine', 'a tool that makes work easier', 'A pulley is a simple machine.', ALL, 'Basic Science'],
  ['energy', 'the ability to do work', 'The sun gives us light energy.', ALL, 'Basic Science'],
  ['temperature', 'how hot or cold something is', 'The nurse checked my temperature.', ALL, 'Basic Science'],
  ['thermometer', 'an instrument that measures temperature', 'Read the thermometer carefully.', ALL, 'Basic Science'],
  ['pollution', 'making air, water or land dirty', 'Smoke causes air pollution.', ALL, 'Basic Science'],
  ['erosion', 'the washing away of soil', 'Heavy rain caused erosion near the road.', HIGH, 'Basic Science'],
  ['insect', 'a small animal with six legs', 'An ant is an insect.', ALL, 'Basic Science'],
  ['mammal', 'an animal that feeds its young with milk', 'A goat is a mammal.', ALL, 'Basic Science'],
  ['reptile', 'a cold-blooded animal with scaly skin', 'The lizard is a reptile.', ALL, 'Basic Science'],
  ['digestion', 'breaking down food in the body', 'The digestion of food begins in the mouth.', HIGH, 'Basic Science'],
  // Computer Studies
  ['computer', 'an electronic machine that processes data', 'We type stories on the computer.', ALL, 'Computer Studies'],
  ['software', 'the programs a computer runs', 'Install the software carefully.', ALL, 'Computer Studies'],
  ['monitor', 'the screen of a computer', 'The monitor shows pictures and words.', ALL, 'Computer Studies'],
  ['password', 'a secret word used to log in', 'Never share your password.', ALL, 'Computer Studies'],
  // Social Studies and Civic Education
  ['citizen', 'a member of a country', 'A good citizen obeys the law.', ALL, 'Civic Education'],
  ['pledge', 'a solemn promise', 'We say the national pledge at assembly.', ALL, 'Civic Education'],
  ['anthem', 'a song of a nation', 'We sang the national anthem.', ALL, 'Civic Education'],
  ['president', 'the head of a country like Nigeria', 'The president lives in Abuja.', ALL, 'Civic Education'],
  ['judiciary', 'the arm of government that interprets laws', 'The judiciary interprets the law.', HIGH, 'Civic Education'],
  ['culture', 'the way of life of a people', 'Dancing is part of our culture.', ALL, 'Social Studies'],
  ['festival', 'a special time of celebration', 'The Argungu festival is held in Kebbi State.', ALL, 'Social Studies'],
  ['ceremony', 'a formal event for a special occasion', 'The naming ceremony was on Saturday.', ALL, 'Social Studies'],
  ['transport', 'moving people or goods from place to place', 'The bus is a means of transport.', ALL, 'Social Studies'],
  ['communication', 'sharing information and messages', 'The phone is a means of communication.', HIGH, 'Social Studies'],
  // History
  ['kingdom', 'a land ruled by a king or queen', 'Benin was a famous kingdom in the south.', HIGH, 'History'],
  ['empire', 'many lands ruled by one ruler', 'Oyo was once a powerful empire.', HIGH, 'History'],
  // Agricultural Science
  ['harvest', 'gathering crops when they are ready', 'The farmers gathered a big harvest of maize.', ALL, 'Agricultural Science'],
  ['fertiliser', 'a substance added to soil to help plants grow', 'The farmer added fertiliser to the soil.', HIGH, 'Agricultural Science'],
  ['poultry', 'birds kept for eggs and meat', 'Uncle Musa keeps poultry behind his house.', ALL, 'Agricultural Science'],
  ['cutlass', 'a long knife used on the farm', 'Use the cutlass with care.', ALL, 'Agricultural Science'],
  // Home Economics
  ['hygiene', 'keeping clean to stay healthy', 'Good hygiene keeps us healthy.', ALL, 'Home Economics'],
  ['laundry', 'clothes that need washing', 'Mother does the laundry on Saturday.', ALL, 'Home Economics'],
  ['kitchen', 'the room where food is cooked', 'Keep the kitchen clean.', ALL, 'Home Economics'],
  ['nutritious', 'full of what the body needs', 'Beans porridge is nutritious.', HIGH, 'Home Economics'],
  ['needle', 'a thin pointed tool for sewing', 'Thread the needle carefully.', ALL, 'Home Economics'],
]);
